import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readdir} from 'node:fs/promises';
const files=(await readdir(new URL('../content/lessons/',import.meta.url))).filter(f=>/^\d.*\.js$/.test(f));
const lessons=await Promise.all(files.map(async f=>(await import(new URL('../content/lessons/'+f,import.meta.url))).default));
async function activity(page,a){
 const group=()=>page.getByRole('group',{name:a.question,exact:true});
 if(a.type==='computerChallenge'){if(!await page.locator('.component-list').evaluate(e=>e.open))await page.locator('.component-list summary').click();for(const [i,name] of ['Pamięć RAM','Procesor','Karta graficzna','Dysk SSD M.2'].entries()){await page.locator('.component-list').getByRole('button',{name:new RegExp(name)}).click();if(i<3)await page.getByRole('button',{name:'Następny element'}).click();}}
 if(a.type==='choice')await group().getByRole('button').nth(a.correct[0]).click();
 if(a.type==='multi'){const g=group();for(const i of a.correct||Array.from({length:a.min||1},(_,i)=>i))await g.getByRole('checkbox').nth(i).check();await g.getByRole('button',{name:'Sprawdź wybór'}).click();}
 if(a.type==='hardware')await page.getByRole('button',{name:'Wybieram',exact:true}).nth(1).click();
 if(a.type==='matching')for(let i=0;i<a.rows.length;i++)await page.locator(`#${a.id}-${i}`).selectOption(String(a.rows[i].correct[0]));
 if(a.type==='sort')for(let i=0;i<a.files.length;i++){const [n,f]=a.files[i];const file=page.getByRole('button',{name:n,exact:true});const folder=page.getByRole('button',{name:`Przenieś wybrany plik do folderu ${a.folders[f]}`});if(i===0)await file.dragTo(folder);else{await file.click();await folder.click();}}
 if(a.type==='text'){await page.locator(`#${a.id}`).fill(a.mode==='filename'?'Plan_wycieczki_Krakow_2026.docx':'RAM, bo pracuję z wieloma aplikacjami');await page.locator('form').filter({has:page.locator(`#${a.id}`)}).getByRole('button').click();}
 if(a.type==='scenarios')for(const c of a.cases){const d=page.locator('details.scenario').filter({has:page.locator('summary').filter({hasText:c.title})});await d.locator('summary').click();for(const i of c.correct)await d.getByRole('checkbox').nth(i).check();await d.getByRole('button',{name:'Sprawdź wybór'}).click();}
 if(a.type==='sequence'){for(const i of a.correct)await page.getByRole('button',{name:a.options[i],exact:false}).click();await page.getByRole('button',{name:'Sprawdź kolejność'}).click();}
 if(a.type==='appNeeds'){await page.locator(`#${a.id}`).selectOption(a.categories[1]);await page.getByRole('checkbox',{name:'Kamera',exact:true}).check();await page.locator(`#${a.id}-reason`).fill('Wysłanie zdjęcia w wiadomości');await page.getByRole('button',{name:'Porównaj z przykładami'}).click();}
 if(a.type==='checklist')for(const item of a.items)await page.getByRole('checkbox',{name:item,exact:true}).check();
 if(a.type==='flow')for(let i=1;i<a.nodes.length;i++)await page.getByRole('button',{name:'Odkryj kolejny krok'}).click();
}
test('Home, future classes, keyboard navigation and accessibility',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./');await expect(page.getByRole('heading',{name:'Twoje lekcje'})).toBeVisible();await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'Przejdź do treści'})).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('main')).toBeFocused();await page.getByRole('button',{name:'Klasa 2'}).click();await expect(page.getByRole('heading',{name:'Klasa 2: kolejne lekcje przed nami.'})).toBeVisible();await page.getByRole('button',{name:'Przejdź do klasy 1'}).click();const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations).toEqual([]);await page.screenshot({path:'tmp/qa-home-desktop.png',fullPage:true});expect(errors).toEqual([]);});
for(const lesson of lessons)test(`Lesson ${lesson.id}: all six stages and local persistence`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`./lesson/${lesson.id}/`);await expect(page.getByRole('heading',{name:lesson.title,exact:true})).toBeVisible();for(let i=0;i<lesson.sections.length;i++){const s=lesson.sections[i];await expect(page.getByRole('heading',{name:s.title,exact:true})).toBeVisible();for(const a of s.activities)await activity(page,a);await page.getByRole('button',{name:i===5?'Zakończ lekcję':'Przejdź dalej',exact:true}).click();}await expect(page.getByRole('heading',{name:'Lekcja ukończona.'})).toBeVisible();await page.reload();await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','6');await page.getByRole('button',{name:'Prowadzę lekcję'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Poprzedni etap'}).click();await expect(page.getByRole('dialog').getByRole('heading',{name:lesson.sections[4].title})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();expect(errors).toEqual([]);});
test('Mobile widths, every stage, drawer accessibility, direct teacher routes and downloads',async({page})=>{
 for(const width of [390,768]){await page.setViewportSize({width,height:844});for(const l of lessons){await page.goto(`./lesson/${l.id}/`);for(let i=0;i<6;i++){await page.getByRole('navigation',{name:'Etapy lekcji'}).getByRole('button').nth(i).click();await expect(page.getByRole('heading',{name:l.sections[i].title,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);} } }
 await page.setViewportSize({width:390,height:844});await page.goto('./lesson/03/');await page.getByRole('navigation',{name:'Etapy lekcji'}).getByRole('button').nth(3).click();await page.getByRole('button',{name:'HDMI',exact:true}).click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'tmp/qa-ports-mobile.png',fullPage:true});
 const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations).toEqual([]);
 await page.getByRole('button',{name:'Prowadzę lekcję'}).click();const drawer=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(drawer.violations).toEqual([]);await page.keyboard.press('Escape');
 for(const l of lessons){await page.goto(`./teacher/lesson/${l.id}/`);await expect(page.getByRole('heading',{name:l.title,exact:true})).toBeVisible();await page.pdf({path:`tmp/teacher-${l.id}.pdf`,format:'A4',printBackground:true});const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations).toEqual([]);}
 const download=await page.request.get('./materials/lesson-02-files.zip');expect(download.status()).toBe(200);expect((await download.body()).subarray(0,2).toString()).toBe('PK');
});
test('Wrong answer, skipped stage and reset never imply a finished lesson',async({page})=>{await page.goto('./lesson/01/');await page.getByRole('button',{name:'Przejdź dalej',exact:true}).click();await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await page.getByRole('navigation',{name:'Etapy lekcji'}).getByRole('button').nth(2).click();if(!await page.locator('.component-list').evaluate(e=>e.open))await page.locator('.component-list summary').click();await page.locator('.component-list').getByRole('button',{name:'Obudowa',exact:true}).click();await expect(page.getByRole('status')).toContainText('Spróbuj jeszcze raz');await page.getByRole('button',{name:'Wyczyść mój postęp'}).click();await page.getByRole('button',{name:'Wyczyść postęp',exact:true}).click();await expect(page.getByRole('heading',{name:'Twoje lekcje'})).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('informatyka-praktycznie-v1')))).toEqual({});});
