import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readdir} from 'node:fs/promises';
import {createDentalProject,prepareDentalRecords,performDentalQueries} from './dental-helpers.js';
const files=(await readdir(new URL('../content/lessons/',import.meta.url))).filter(f=>/^\d.*\.js$/.test(f));
const lessons=await Promise.all(files.map(async f=>(await import(new URL('../content/lessons/'+f,import.meta.url))).default));
async function activity(page,a){
 if(a.type==='dentalSimulator'){if(a.mode==='create'){await createDentalProject(page);await prepareDentalRecords(page);}else await performDentalQueries(page);}
 const group=()=>page.getByRole('group',{name:a.question,exact:true});
 if(a.type==='computerChallenge'){if(!await page.locator('.component-list').evaluate(e=>e.open))await page.locator('.component-list summary').click();for(const [i,name] of ['Pamięć RAM','Procesor','Karta graficzna','Dysk SSD M.2'].entries()){await page.locator('.component-list').getByRole('button',{name:new RegExp(name)}).click();if(i<3)await page.getByRole('button',{name:'Następny element'}).click();}}
 if(a.type==='choice')await group().locator(`button[data-option="${a.correct[0]}"]`).click();
 if(a.type==='multi'){const g=group();for(const i of a.correct||Array.from({length:a.min||1},(_,i)=>i))await g.locator(`label[data-option="${i}"] input`).check();await g.getByRole('button',{name:'Sprawdź wybór'}).click();}
 if(a.type==='hardware')await page.getByRole('button',{name:'Wybieram',exact:true}).nth(1).click();
 if(a.type==='matching')for(let i=0;i<a.rows.length;i++)await page.locator(`#${a.id}-${i}`).selectOption(String(a.rows[i].correct[0]));
 if(a.type==='sort')for(let i=0;i<a.files.length;i++){const [n,f]=a.files[i];const file=page.getByRole('button',{name:n,exact:true});const folder=page.getByRole('button',{name:`Przenieś wybrany plik do folderu ${a.folders[f]}`});if(i===0)await file.dragTo(folder);else{await file.click();await folder.click();}}
 if(a.type==='text'){await page.locator(`#${a.id}`).fill(a.mode==='filename'?'Plan_wycieczki_Krakow_2026.docx':'RAM, bo pracuję z wieloma aplikacjami');await page.locator('form').filter({has:page.locator(`#${a.id}`)}).getByRole('button').click();}
 if(a.type==='scenarios')for(const c of a.cases){const d=page.locator('details.scenario').filter({has:page.locator('summary').filter({hasText:c.title})});await d.locator('summary').click();for(const i of c.correct)await d.locator(`label[data-option="${i}"] input`).check();await d.getByRole('button',{name:'Sprawdź wybór'}).click();}
 if(a.type==='sequence'){const box=page.locator('.activity').filter({has:page.getByRole('heading',{name:a.question,exact:true})});for(const i of a.correct)await box.locator(`button[data-option="${i}"]`).click();await box.getByRole('button',{name:'Sprawdź kolejność'}).click();}
 if(a.type==='appNeeds'){await page.locator(`#${a.id}`).selectOption(a.categories[1]);await page.getByRole('checkbox',{name:'Kamera',exact:true}).check();await page.locator(`#${a.id}-reason`).fill('Wysłanie zdjęcia w wiadomości');await page.getByRole('button',{name:'Porównaj z przykładami'}).click();}
 if(a.type==='checklist')for(const item of a.items)await page.getByRole('checkbox',{name:item,exact:true}).check();
 if(a.type==='flow')for(let i=1;i<a.nodes.length;i++)await page.getByRole('button',{name:'Odkryj kolejny krok'}).click();
}
test('Home, all classes, keyboard navigation and accessibility',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('./');await expect(page.getByRole('heading',{name:'Wybierz swoją klasę'})).toBeVisible();await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'Przejdź do treści'})).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('main')).toBeFocused();await page.getByRole('button',{name:'Klasa 2'}).click();await expect(page.getByRole('heading',{name:lessons.find(l=>l.grade===2).title})).toBeVisible();await page.getByRole('button',{name:'Klasa 3'}).click();await expect(page.getByRole('heading',{name:lessons.find(l=>l.grade===3).title})).toBeVisible();await page.getByRole('button',{name:'Klasa 1'}).click();const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations).toEqual([]);await page.screenshot({path:'tmp/qa-home-desktop.png',fullPage:true});expect(errors).toEqual([]);});
for(const lesson of lessons.filter(l=>Number(l.id)<=6))test(`Lesson ${lesson.id}: all six stages and cleared progress after reload`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`./lesson/${lesson.id}/`);await expect(page.getByRole('heading',{name:lesson.title,exact:true})).toBeVisible();for(let i=0;i<lesson.sections.length;i++){const s=lesson.sections[i];await expect(page.getByRole('heading',{name:s.title,exact:true})).toBeVisible();for(const a of s.activities)await activity(page,a);await page.getByRole('button',{name:i===5?'Zakończ lekcję':'Przejdź dalej',exact:true}).click();}await expect(page.getByRole('heading',{name:'Lekcja ukończona.'})).toBeVisible();await page.reload();await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await page.getByRole('button',{name:'Prowadzę lekcję'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Następny etap'}).click();await expect(page.getByRole('dialog').getByRole('heading',{name:lesson.sections[1].title})).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();expect(errors).toEqual([]);});
for(const lesson of lessons.filter(l=>Number(l.id)>6))test(`Lesson ${lesson.id}: every stage renders, result card and accessibility`,async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/favicon/.test(m.text()))errors.push(m.text());});await page.goto(`./lesson/${lesson.id}/`);await expect(page.getByRole('heading',{name:lesson.title,exact:true})).toBeVisible();const last=lesson.sections.length-1;for(let i=0;i<=last;i++){const s=lesson.sections[i];await expect(page.getByRole('heading',{name:s.title,exact:true})).toBeVisible();await expect(page.getByText('Przygotowuję symulator…')).toHaveCount(0);const axe=await new AxeBuilder({page}).include('.lesson-stage').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations.map(v=>`${s.id}: ${v.id} ${v.nodes[0]?.target}`)).toEqual([]);if(i<last)await page.getByRole('button',{name:'Przejdź dalej',exact:true}).click();}await expect(page.locator('.result-card')).toBeVisible();await expect(page.locator('.result-score')).toContainText('/');await page.getByRole('button',{name:'Zakończ lekcję',exact:true}).click();await expect(page.getByRole('heading',{name:'Jeszcze chwila na sprawdzenie.'})).toBeVisible();expect(errors).toEqual([]);});
test('Mobile widths, every stage, drawer accessibility, direct teacher routes and downloads',async({page})=>{
 test.setTimeout(600000);
 for(const width of [390,768]){await page.setViewportSize({width,height:844});for(const l of lessons){await page.goto(`./lesson/${l.id}/`);for(let i=0;i<l.sections.length;i++){await page.getByRole('navigation',{name:'Etapy lekcji'}).getByRole('button').nth(i).click();await expect(page.getByRole('heading',{name:l.sections[i].title,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);} } }
 await page.setViewportSize({width:390,height:844});await page.goto('./lesson/03/');await page.getByRole('navigation',{name:'Etapy lekcji'}).getByRole('button').nth(3).click();await page.getByRole('button',{name:'HDMI',exact:true}).click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'tmp/qa-ports-mobile.png',fullPage:true});
 const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations).toEqual([]);
 await page.getByRole('button',{name:'Prowadzę lekcję'}).click();const drawer=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(drawer.violations).toEqual([]);await page.keyboard.press('Escape');
 for(const l of lessons){await page.goto(`./teacher/lesson/${l.id}/`);await expect(page.getByRole('heading',{name:l.title,exact:true})).toBeVisible();await page.pdf({path:`tmp/teacher-${l.id}.pdf`,format:'A4',printBackground:true});const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations).toEqual([]);}
 const download=await page.request.get('./materials/lesson-02-files.zip');expect(download.status()).toBe(200);expect((await download.body()).subarray(0,2).toString()).toBe('PK');
});
test('Wrong answer, skipped stage and reset never imply a finished lesson',async({page})=>{await page.goto('./lesson/01/');await page.getByRole('button',{name:'Przejdź dalej',exact:true}).click();await expect(page.getByRole('progressbar')).toHaveAttribute('aria-valuenow','0');await page.getByRole('navigation',{name:'Etapy lekcji'}).getByRole('button').nth(2).click();if(!await page.locator('.component-list').evaluate(e=>e.open))await page.locator('.component-list summary').click();await page.locator('.component-list').getByRole('button',{name:'Obudowa',exact:true}).click();await expect(page.locator('.find-feedback')).toContainText('Spróbuj jeszcze raz');await page.getByRole('button',{name:'Wyczyść mój postęp'}).click();await page.getByRole('button',{name:'Wyczyść postęp',exact:true}).click();await expect(page.getByRole('heading',{name:'Wybierz swoją klasę'})).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('informatyka-praktycznie-v1')))).toEqual({});});
test('Fresh start button clears the previous student and reloads without a class',async({page})=>{await page.goto('./lesson/06/');await page.getByRole('button',{name:'Procesor',exact:false}).first().click();await page.getByRole('button',{name:'Przejdź dalej',exact:true}).click();expect(await page.evaluate(()=>localStorage.getItem('informatyka-praktycznie-v1'))).toContain('"06"');await page.goto('./#/klasa/3');await expect(page.getByRole('button',{name:/Klasa 3/})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Wyczyść i zacznij od nowa'}).click();await expect(page.getByRole('heading',{name:'Gotowe — pamięć strony wyczyszczona.'})).toBeVisible();await expect(page.getByRole('heading',{name:'Wybierz swoją klasę'})).toBeVisible();await expect(page.locator('.grade-card.active')).toHaveCount(0);expect(await page.evaluate(()=>location.hash)).toBe('');expect(await page.evaluate(()=>localStorage.getItem('informatyka-praktycznie-v1'))).not.toContain('"06"');await page.reload();await expect(page.getByRole('heading',{name:'Siadasz do komputera po kimś innym?'})).toBeVisible();const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations).toEqual([]);});
