// Short explanations complement the activities; examples are not graded answers.
export const lessonNotes = {
 '01': {
  start:{title:'Od potrzeb do parametrów',paragraphs:['Sprzęt to fizyczne części komputera, a oprogramowanie to programy, które na nim działają. Dobry wybór zaczyna się od trzech pytań: co będę robić, jakie wymagania mają moje programy i ile mogę wydać?','GB i TB opisują ilość danych, a nie szybkość komputera. W specyfikacjach dysków 1 TB oznacza 1000 GB. Pojemności RAM i SSD nie dodajemy do siebie: pełnią inne funkcje.']},
  knowledge:{title:'Cztery części, cztery różne zadania',paragraphs:['CPU, czyli procesor, wykonuje instrukcje programu. RAM jest pamięcią roboczą: trzyma dane używane teraz i traci je po wyłączeniu zasilania. SSD przechowuje pliki także bez zasilania. GPU wykonuje m.in. obliczenia potrzebne do tworzenia obrazu.','Gdy otwierasz prezentację, jej plik jest odczytywany z dysku. Program pracuje z danymi w RAM, procesor wykonuje polecenia, a układ graficzny pomaga wyświetlić efekt. Aby zachować zmiany, trzeba je zapisać.','Płyta główna łączy części, zasilacz dostarcza im energię, a chłodzenie odprowadza ciepło. W laptopie te funkcje pozostają podobne, choć części są mniejsze i częściej zintegrowane. W modelu kliknij najpierw CPU, RAM, SSD i GPU.']},
  check:{title:'Rozpoznaj po funkcji i wyglądzie',paragraphs:['Procesor jest niewielkim układem w gnieździe płyty głównej, zwykle schowanym pod chłodzeniem. Moduły RAM to wąskie płytki w długich gniazdach. Pokazana karta graficzna jest większą płytą z chłodzeniem, a SSD M.2 przypomina mały pasek z układami.','To wskazówki dla tego modelu. Układ graficzny może być częścią procesora, RAM bywa wlutowany, a SSD występuje także w innych obudowach. Funkcja części jest ważniejsza od jej koloru czy rozmiaru.']},
  practice:{title:'Jak uzasadnić wybór?',paragraphs:['Użyj zdania: „Wybieram…, ponieważ ta osoba robi…, a parametr… pomoże jej w…”. Sprawdź także cenę. Samo „C jest najlepszy” nie wyjaśnia, czy jego możliwości będą potrzebne.','Duża liczba GB nie mówi wszystkiego. W procesorach i kartach graficznych liczy się konkretny model oraz wymagania programu. Z naszych uproszczonych kart nie da się obliczyć liczby klatek w grze.'],example:{question:'Przykład: nauka z kilkoma aplikacjami i budżet 2600 zł',answer:'Wybrałbym B: mieści się w budżecie, 16 GB RAM daje większy zapas do wielu aplikacji niż 4 GB w A, a SSD 512 GB pomieści więcej materiałów. C przekracza budżet. To uzasadnienie do fikcyjnych konfiguracji, nie oferta zakupu.'}},
  decide:{title:'Znajdź to, co ogranicza pracę',paragraphs:['Jeżeli brakuje miejsca na filmy, ważna jest pojemność dysku. Jeśli wiele otwartych programów zużywa pamięć roboczą, warto przyjrzeć się RAM. Płynność gry zależy m.in. od CPU, GPU, ustawień i samej gry.','Jedno spowolnienie nie wystarcza do rozpoznania przyczyny. Najpierw określ zadanie i sprawdź wymagania programu; dopiero potem wybieraj parametr.']},
  summary:{title:'Notatka do powtórki',paragraphs:['CPU wykonuje instrukcje, RAM przechowuje bieżące dane, SSD zachowuje pliki, a GPU pomaga tworzyć obraz. Płyta główna, zasilacz i chłodzenie umożliwiają ich wspólną pracę.','Dobieraj sprzęt do zastosowań, wymagań programów i budżetu. Potrafisz uzasadnić wybór, gdy łączysz konkretny parametr z konkretną potrzebą.'],example:{question:'Sprawdź swoje wyjaśnienie: czy większy SSD zastąpi RAM?',answer:'Nie. Większy SSD daje więcej miejsca na zapisane dane, ale nie zwiększa pojemności fizycznej pamięci RAM. System może używać dysku jako wsparcia pamięci, jednak nie działa to tak samo jak dodatkowy RAM.'}}
 },
 '02': {
  start:{title:'Zapisany plik to coś więcej niż nazwa',paragraphs:['Plik ma nazwę, format, rozmiar i miejsce zapisu. Folder porządkuje pliki. Ścieżka pokazuje, jak do nich trafić, np. Szkoła → Informatyka → Lekcja_02 → Notatka.txt.','Przed rozpoczęciem pracy ustal folder docelowy. „Pobrane” jest wygodne na chwilę, ale nie musi być dobrym miejscem na wszystkie szkolne materiały.']},
  knowledge:{title:'Co robi system, a co aplikacja?',paragraphs:['System operacyjny zarządza pamięcią, urządzeniami, plikami i uruchamianiem programów. Aplikacja korzysta z tych usług: edytor pozwala pisać, a przeglądarka otwiera strony. Menedżer plików służy do wyszukiwania i porządkowania zapisanych danych.','Zainstalowanie aplikacji udostępnia ją w systemie. Otwarcie pliku uruchamia zgodny program, a zapis utrwala zmiany. Zamknięcie okna nie zawsze oznacza zapisanie pracy.','Rozszerzenie, np. .docx lub .jpg, wskazuje format. Jeśli końcówki są ukryte, sprawdź typ pliku w jego właściwościach lub włącz ich wyświetlanie. Sama zmiana .jpg na .pdf nie tworzy dokumentu PDF.']},
  sort:{title:'Kopiowanie i przenoszenie',paragraphs:['Kopiowanie tworzy drugi egzemplarz i zostawia oryginał. Przenoszenie zmienia miejsce pliku. Najłatwiej świadomie wybrać polecenia Kopiuj lub Wytnij, a potem Wklej w folderze docelowym; samo przeciąganie może zachowywać się różnie.','W tym ćwiczeniu grupujemy według rodzaju danych. W codziennej pracy możesz porządkować według przedmiotu lub projektu. Ważne, by zasada była czytelna i konsekwentna.']},
  names:{title:'Nazwa ma pomagać w szukaniu',paragraphs:['Dobry wzór to temat + miejsce lub data + ewentualna wersja, np. Plan_wycieczki_Krakow_2026_v2.docx. Zachowaj rozszerzenie. Nie dopisuj go drugi raz, jeśli menedżer plików ukrywa końcówki.','Przed usunięciem starszej wersji sprawdź zawartość. Kosz może umożliwić odzyskanie pliku, ale nie dotyczy to każdego sposobu usuwania i każdego nośnika. Ważne materiały przechowuj także w kopii zapasowej.']},
  zip:{title:'ZIP: pakowanie i rozpakowanie',paragraphs:['ZIP jest archiwum: łączy pliki i strukturę folderów w jedną paczkę. Kompresja może zmniejszyć rozmiar, ale zdjęcia JPG i filmy MP4 często są już skompresowane.','Aby rozpakować paczkę, znajdź ją w menedżerze plików, wybierz funkcję wyodrębniania lub rozpakowania i wskaż folder docelowy. Pracuj w tym folderze. Aby utworzyć ZIP, zaznacz uporządkowany folder i wybierz funkcję kompresowania do ZIP. Nazwy poleceń zależą od systemu.']},
  summary:{title:'Instrukcja pracy samodzielnej',paragraphs:['Pobierz paczkę poniżej i rozpakuj ją do nowego folderu Lekcja_02. Utwórz w nim Dokumenty, Zdjęcia i Filmy. Przenieś pliki według rodzaju; folder docelowy otwieraj przed wklejeniem.','Nazwy zmieniaj na podstawie zawartości, a nie domysłów. W paczce obrazy są planszami testowymi. Dokument.docx otwórz w zgodnym edytorze. Jeśli pracujesz tylko na telefonie, wykonaj część na stronie, a zadanie z plikami dokończ na komputerze.','Gotowy folder spakuj do nowego ZIP. Rozpakuj własne archiwum w innym miejscu i sprawdź: trzy foldery, łącznie 10 plików, czytelne nazwy i możliwość otwarcia plików. To dowód wykonania zadania; same zaznaczenia na stronie go nie zastępują.'],example:{question:'Wzór sprawdzenia zawartości',answer:'Dokumenty: 6 plików (trzy DOCX, PDF, TXT i PPTX). Zdjęcia: 3 pliki (dwa JPG i PNG). Filmy: 1 MP4. Przykładowe nowe nazwy: Plan_wycieczki_Krakow_2026.docx i Plansza_zielona.jpg.'}}
 },
 '03': {
  start:{title:'Objaw to jeszcze nie przyczyna',paragraphs:['„Brak sygnału” mówi, że projektor nie otrzymuje oczekiwanego obrazu. Przyczyną może być kabel, niewłaściwe wejście lub ustawienie laptopa — niekoniecznie awaria projektora.','Diagnostyka polega na sprawdzaniu możliwych przyczyn. Zmieniaj jedną rzecz naraz i obserwuj efekt. Dzięki temu wiesz, co pomogło.']},
  model:{title:'Prześledź drogę sygnału',paragraphs:['W prezentacji sygnał biegnie od laptopa przez kabel do wejścia projektora. Projektor musi mieć zasilanie i wybrane to wejście, do którego podłączono przewód. Laptop musi wysyłać obraz na ekran zewnętrzny.','Duplikowanie pokazuje ten sam obraz na obu ekranach. Rozszerzenie tworzy większy pulpit: okno może znajdować się poza ekranem laptopa. Przy prezentowaniu sprawdź podgląd, zanim pokażesz klasie prywatne okna.'],example:{question:'Przykład kontroli krok po kroku',answer:'Projektor jest włączony. Kabel jest podłączony do HDMI 2, lecz wybrane źródło to HDMI 1. Wybieram HDMI 2 i sprawdzam obraz. Jeśli pojawia się prezentacja, nie wykonuję już restartu.'}},
  cases:{title:'Nie działa wszędzie czy tylko w jednej aplikacji?',paragraphs:['Jeśli dźwięk działa w jednej aplikacji, a w drugiej nie, sprawdź ustawienia tej drugiej. Jeśli nie działa nigdzie, sprawdź połączenie i systemowe wyjście audio. Podobnie wybiera się mikrofon lub kamerę.','Drukarka może czekać na papier albo mieć w kolejce wcześniejsze zadanie. Odczytaj komunikat i sprawdź wybraną drukarkę. Nie wysyłaj wielu kopii tego samego dokumentu.','Kontroluj wyłącznie dostępne przewody i ustawienia, zgodnie z zasadami pracowni. Uszkodzony kabel, zapach spalenizny lub nietypowe nagrzewanie zgłoś nauczycielowi. Nie otwieraj urządzenia.']},
  ports:{title:'Kształt wtyczki i funkcja połączenia',paragraphs:['HDMI i DisplayPort przesyłają obraz i dźwięk. USB służy m.in. do danych i zasilania. Jack przenosi sygnał audio. Sprawdź oba końce przewodu, a wtyczkę wkładaj bez używania siły.','USB-C opisuje kształt złącza. Sam wygląd nie potwierdza szybkości transmisji, mocy ładowania ani obsługi obrazu. Potrzebną funkcję muszą obsługiwać urządzenie, port oraz użyty kabel lub adapter.']},
  adapter:{title:'Jak sprawdzić adapter?',paragraphs:['Zapisz, skąd i dokąd ma płynąć sygnał: laptop USB-C → projektor HDMI. Sprawdź w specyfikacji laptopa obsługę wyjścia obrazu, a w opisie adaptera jego kierunek i zgodność.','Pasujące końcówki nie gwarantują działania. Niektóre adaptery działają tylko w jednym kierunku. Jeśli sprzęt należy do szkoły, poproś o sprawdzony przewód lub pomoc nauczyciela.']},
  summary:{title:'Notatka i zgłoszenie problemu',paragraphs:['Kolejność pomocnicza: zasilanie → połączenie → właściwe urządzenie → ustawienia → ewentualny restart po zapisaniu pracy. Po każdej zmianie sprawdzaj efekt.','Gdy problem zostaje, zgłoś objaw, nazwę urządzenia i wykonane kontrole. Taki opis jest użyteczniejszy niż „nie działa”.'],example:{question:'Przykład dobrego zgłoszenia',answer:'Projektor pokazuje „Brak sygnału”. Jest włączony, kabel sprawdzony po obu stronach, wybrane HDMI 2 odpowiada użytemu gniazdu. Po włączeniu duplikowania nadal brak obrazu. Proszę o pomoc w sprawdzeniu kabla lub portu.'}}
 },
 '04': {
  start:{title:'Urządzenie zbiera, przetwarza i przesyła dane',paragraphs:['Telefon, telewizor i inteligentny głośnik to komputery o różnych zadaniach. Czujnik zbiera dane, program je interpretuje, a połączenie pozwala wymienić informacje z innym urządzeniem lub usługą.','Przy każdej funkcji pytaj: skąd są dane, co je przetwarza i dokąd są przesyłane? Na przykład mikrofon zbiera głos, a aplikacja może go nagrać albo przesłać rozmówcy.']},
  technologies:{title:'Sieć domowa a Internet',paragraphs:['Wi-Fi łączy urządzenie z lokalną siecią, zwykle przez router. Router kieruje ruchem między sieciami. Dostęp do Internetu wymaga jeszcze działającego połączenia z operatorem. Dlatego ikona Wi-Fi nie oznacza, że każda strona się otworzy.','Bluetooth zwykle łączy pobliskie urządzenia, np. telefon i słuchawki. NFC służy komunikacji z bardzo bliska. GPS dostarcza sygnałów do ustalenia pozycji; nie jest sposobem wysyłania wiadomości.'],example:{question:'Mapa bez Internetu — czy to możliwe?',answer:'Telefon może ustalić pozycję z sygnałów satelitarnych, a mapa pobrana wcześniej może ją pokazać offline. Aktualny ruch drogowy lub pobranie nowego obszaru zwykle wymagają połączenia z usługą.'}},
  match:{title:'Przykłady z domu',paragraphs:['Telewizor może pobierać film przez Wi-Fi lub kabel sieciowy. Słuchawki odbierają dźwięk przez Bluetooth. Telefon może odczytać tag NFC. Są to różne połączenia, choć z perspektywy użytkownika wszystko dzieje się „bez kabla”.','Jedna czynność może łączyć kilka technologii: telefon pobiera muzykę przez Wi-Fi, a potem wysyła dźwięk do słuchawek przez Bluetooth. Brak Internetu nie musi przerwać odtwarzania wcześniej pobranego pliku.']},
  sensors:{title:'Pomiar nie jest jeszcze decyzją',paragraphs:['Czujnik światła mierzy warunki oświetlenia; system może na tej podstawie zmienić jasność ekranu. Akcelerometr i żyroskop dostarczają danych o ruchu; program decyduje, czy obrócić obraz. Blokada obrotu może zatrzymać tę zmianę mimo działającego czujnika.','Kamera dostarcza obrazu, a oprogramowanie może np. odczytać kod QR. Nie każda analiza wymaga serwera: część obliczeń odbywa się na urządzeniu, część w usłudze online. Zależy to od funkcji i aplikacji.']},
  service:{title:'Co to jest serwer?',paragraphs:['Serwer to komputer lub program obsługujący żądania innych urządzeń. Aplikacja wysyła do usługi zamówienie, a usługa odsyła odpowiedź. Użytkownik widzi przycisk i komunikat, ale po drodze trwa wymiana danych.','W przykładzie przejazdu lokalizacja pomaga wskazać odbiór, Internet przesyła zamówienie, a serwer organizuje obsługę zgłoszenia. GPS nie przesyła zamówienia kierowcy. Gdy brak połączenia, samo wskazanie pozycji nie potwierdza zamówienia.']},
  summary:{title:'Uprawnienie dobieraj do czynności',paragraphs:['Nagranie wiadomości wymaga dostępu do mikrofonu, zdjęcie — do kamery. Wpisanie adresu ręcznie może zastąpić odczyt lokalizacji. Zawsze łącz dostęp z konkretną funkcją, nie z samą nazwą aplikacji.','Odmowa dostępu może wyłączyć daną funkcję; nie musi blokować całej aplikacji. Uprawnienia można sprawdzić w ustawieniach systemu. Internet, Bluetooth i NFC w zadaniu oznaczają też potrzebne połączenia — nie wszystkie systemy przedstawiają je jako takie same pytania o zgodę.','Do powtórki: czujnik zbiera dane, oprogramowanie je przetwarza, połączenie je przenosi, a uprawnienia regulują część dostępu do zasobów urządzenia.'],example:{question:'Przykład uzasadnienia dla komunikatora',answer:'Do wysłania wpisanej wiadomości potrzebuję połączenia z usługą, ale nie kamery ani mikrofonu. Mikrofon będzie potrzebny, gdy wybiorę wiadomość głosową. Odbiorcę mogę czasem wpisać ręcznie, bez udostępniania całej książki kontaktów.'}}
 }
};
