import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {lessons} from '../content/lessons/index.js';
import {Icon} from '../components/icons.jsx';
import {Activity,FeedbackBox} from '../components/activities.jsx';
import {TeacherDrawer,TeacherPlan} from '../components/teacher.jsx';
import './style.css';
import {LessonReading,IndependentStudy} from '../components/lesson-reading.jsx';
import {SiteFooter,ProjectPage} from '../components/project.jsx';

const storageKey='informatyka-praktycznie-v1';
const base=(()=>{const url=new URL(document.baseURI);if(document.querySelector('base'))return url.href;const found=url.pathname.match(/^(.*\/)(?:teacher\/)?lesson\/[^/]+\/?$/);return found?url.origin+found[1]:new URL('./',url).href;})();
function route(){const hash=location.hash.replace(/^#/,'');if(hash)return hash;if(/\/o-projekcie\/?$/.test(location.pathname))return '/project';const p=location.pathname.match(/\/(teacher\/)?lesson\/(\d+)\/?$/);return p?`/${p[1]||''}lesson/${p[2]}`:'/';}
function readSaved(){try{const x=JSON.parse(localStorage.getItem(storageKey));return x&&typeof x==='object'&&!Array.isArray(x)?x:{};}catch{return {};}}
const taskTypes=new Set(['choice','multi','matching','sort','hardware','scenarios','text','sequence','appNeeds','checklist','computerChallenge']);
function sectionDone(s,answers){return s.activities.filter(a=>taskTypes.has(a.type)).every(a=>answers?.[a.id]?.done);}
function LessonCard({lesson,saved}){const count=lesson.sections.filter(s=>saved?.completed?.includes(s.id)).length;return <a className={`lesson-card lesson-${lesson.id}`} href={`${base}#/lesson/${lesson.id}`}><div className="card-visual"><Icon name={lesson.icon} size={100}/><div className="visual-labels">{({'01':['CPU','RAM','SSD','GPU'],'02':['.docx','.jpg','.zip'],'03':['USB-C','HDMI'],'04':['GPS','NFC','Wi-Fi']})[lesson.id]?.map(t=><span key={t}>{t}</span>)}</div></div><div className="card-content"><div className="card-meta"><span>Lekcja {lesson.id}</span><span><Icon name="clock" size={15}/>{lesson.duration} min</span></div><h3>{lesson.title}</h3><p>{lesson.subtitle}</p><div className="card-bottom"><span>{count===6?'Ukończona':count>0?`Kontynuuj · ${count}/6 etapów`:'Otwórz lekcję'}</span><Icon name={count===6?'complete':'right'} size={22}/></div></div></a>}
function Header(){return <header className="site-header"><a href={`${base}#/`} className="brand"><span className="brand-icon"><Icon name="school" size={26}/></span><span>informatyka<span className="brand-second">praktycznie</span></span></a><nav aria-label="Nawigacja główna"><a href={`${base}#/`}>Lekcje</a><a href={`${base}#/teacher`}>Dla nauczyciela <Icon name="book" size={18}/></a></nav></header>}
function Home({saved}){const [grade,setGrade]=useState(1);const items=lessons.filter(l=>l.grade===grade);return <main tabIndex={-1} id="main" className="home"><section className="home-hero"><div className="home-hero-copy"><p className="eyebrow">Technikum · Rok szkolny 2026/2027</p><h1>Informatyka<br/><span>praktycznie.</span></h1><p className="hero-tagline">Zrozum. Sprawdź. Zastosuj.</p></div><a className="home-qr" href="https://www.informatyka.szkolamistrzow.info/" aria-label="Otwórz stronę Informatyka praktycznie"><img src={`${base}qr-informatyka.png`} width="1312" height="1312" alt="Kod QR do strony www.informatyka.szkolamistrzow.info"/><span>Zeskanuj i otwórz stronę</span><small>www.informatyka.<wbr/>szkolamistrzow.info</small></a></section><section className="catalog" aria-labelledby="catalog-title"><div className="catalog-top"><h2 id="catalog-title">Twoje lekcje</h2><span className="muted">{items.length?`${items.length} tematy na początek`:'Materiały pojawią się później'}</span></div><div className="grade-tabs" role="group" aria-label="Wybierz klasę">{[1,2,3].map(g=><button key={g} className={g===grade?'active':''} aria-pressed={g===grade} onClick={()=>setGrade(g)}>Klasa {g}{!lessons.some(l=>l.grade===g)&&<span>Wkrótce</span>}</button>)}</div>{items.length?<div className="lesson-grid">{items.map(l=><LessonCard key={l.id} lesson={l} saved={saved[l.id]}/>)}</div>:<div className="empty-state"><Icon name="book" size={48}/><h3>Klasa {grade}: kolejne lekcje przed nami.</h3><p>Materiały będą dodawane stopniowo. Na razie możesz korzystać z tematów dla klasy 1.</p><button className="btn secondary" onClick={()=>setGrade(1)}>Przejdź do klasy 1 <Icon name="right" size={18}/></button></div>}</section><aside className="home-note"><Icon name="book" size={30}/><div><h2>Prowadzisz zajęcia?</h2><p>Każda lekcja ma wskazówki do kolejnych etapów i plan gotowy do wydrukowania.</p></div><a className="text-button" href={`${base}#/teacher`}>Zobacz plany <Icon name="right" size={19}/></a></aside></main>}
function LessonProgress({lesson,stage,completed,onStage}){return <nav className="lesson-progress" aria-label="Etapy lekcji"><ol>{lesson.sections.map((s,i)=><li key={s.id}><button aria-current={stage===i?'step':undefined} className={`${stage===i?'current':''} ${completed.includes(s.id)?'done':''}`} onClick={()=>onStage(i)}><span>{completed.includes(s.id)?<Icon name="check" size={16}/>:i+1}</span><b>{s.label}</b></button></li>)}</ol><div className="progress-track" role="progressbar" aria-label="Ukończone etapy" aria-valuenow={completed.length} aria-valuemin={0} aria-valuemax={lesson.sections.length}><span style={{width:`${completed.length/lesson.sections.length*100}%`}}/></div></nav>}
function LessonHeader({lesson,onTeacher}){return <div className="lesson-header"><a className="text-button" href={`${base}#/`}><Icon name="left" size={18}/>Wszystkie lekcje</a><button className="btn secondary" onClick={onTeacher}><Icon name="school" size={20}/>Prowadzę lekcję</button><div className="lesson-heading"><p className="eyebrow">Klasa {lesson.grade} · Lekcja {lesson.id} · około {lesson.duration} min</p><h1>{lesson.title}</h1><p>{lesson.subtitle}</p></div></div>}
function Lesson({lesson,saved={},update}){
 const [stage,setStage]=useState(Math.min(Math.max(Number(saved.stage)||0,0),lesson.sections.length-1));const [teacher,setTeacher]=useState(false);const [notice,setNotice]=useState('');const [finish,setFinish]=useState(false);const titleRef=useRef();const answers=saved.answers||{};const completed=(saved.completed||[]).filter(id=>lesson.sections.some(s=>s.id===id));const section=lesson.sections[stage];
 function go(i){setStage(i);update({...saved,stage:i});setNotice('');setFinish(false);setTimeout(()=>{titleRef.current?.focus({preventScroll:true});document.querySelector('.lesson-progress')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});},0);}
 function next(){const done=sectionDone(section,answers);const c=done?[...new Set([...completed,section.id])]:completed.filter(id=>id!==section.id);update({...saved,completed:c,stage:Math.min(stage+1,5)});if(stage<5){setStage(stage+1);setNotice(done?'':'Poprzedni etap nie jest jeszcze ukończony. Możesz do niego wrócić z paska etapów.');setTimeout(()=>{titleRef.current?.focus({preventScroll:true});document.querySelector('.lesson-progress')?.scrollIntoView({behavior:'instant',block:'start'});},0);}else{setFinish(true);setNotice('');}}
 function change(id,v){const a={...answers,[id]:v};const c=completed.filter(s=>s!==section.id||sectionDone(section,a));update({...saved,answers:a,completed:c});setFinish(false);}
 return <main tabIndex={-1} id="main" className="lesson-shell"><LessonHeader lesson={lesson} onTeacher={()=>setTeacher(true)}/><IndependentStudy lessonId={lesson.id}/><LessonProgress lesson={lesson} stage={stage} completed={completed} onStage={go}/><article className="lesson-stage" key={section.id}><div className="stage-meta"><span>Etap {stage+1} / 6 · {section.label}</span><span>{section.duration} min</span></div><h2 ref={titleRef} tabIndex={-1}>{section.title}</h2><p className="stage-intro">{section.intro}</p><LessonReading lessonId={lesson.id} sectionId={section.id}/>{notice&&<InfoNotice>{notice}</InfoNotice>}<div className="activities">{section.activities.map(a=><Activity key={a.id} data={a} value={answers[a.id]} onChange={v=>change(a.id,v)} base={base}/>)}</div>{finish&&<div className="completion" role="status"><Icon name={completed.length===6?'complete':'book'} size={44}/><h3>{completed.length===6?'Lekcja ukończona.':'Jeszcze chwila na sprawdzenie.'}</h3><p>{completed.length===6?lesson.exitTicket:`Ukończone etapy: ${completed.length}/6. Wróć do etapów bez znaku ✓, wykonaj zadania i zatwierdź przyciskiem na dole.`}</p>{completed.length===6?<a href={`${base}#/`} className="btn">Wróć do lekcji <Icon name="right" size={18}/></a>:<button className="btn secondary" onClick={()=>go(lesson.sections.findIndex(s=>!completed.includes(s.id)))}>Wróć do nieukończonego etapu</button>}</div>}<div className="stage-navigation"><button className="text-button" disabled={stage===0} onClick={()=>go(stage-1)}><Icon name="left" size={19}/>Wstecz</button><button className="btn" onClick={next}>{stage===5?'Zakończ lekcję':'Przejdź dalej'}<Icon name={stage===5?'check':'right'} size={19}/></button></div><p className="progress-caption">Ukończone etapy: {completed.length}/6. Odpowiedzi możesz poprawiać.</p></article><TeacherDrawer open={teacher} onClose={()=>setTeacher(false)} lesson={lesson} stage={stage} onStage={go} base={base}/></main>
}
function InfoNotice({children}){return <div className="info-notice" role="status">{children}</div>}
function TeacherIndex(){return <main tabIndex={-1} id="main" className="teacher-index"><p className="eyebrow">Materiały do prowadzenia zajęć</p><h1>Plany lekcji</h1><p className="lead">Cele, pytania do klasy i przebieg minuta po minucie. Otwórz plan i wydrukuj go na A4.</p><div className="teacher-list">{lessons.map(l=><a key={l.id} href={`${base}teacher/lesson/${l.id}/`}><span>{l.id}</span><div><h2>{l.title}</h2><p>Klasa {l.grade} · {l.duration} minut · 6 etapów</p></div><Icon name="right"/></a>)}</div><InfoNotice>Tryb nauczyciela jest dostępny również wewnątrz lekcji pod przyciskiem „Prowadzę lekcję”. Nie wymaga konta.</InfoNotice></main>}
function App(){const [path,setPath]=useState(route),[saved,setSaved]=useState(readSaved),[storageError,setStorageError]=useState(false),[reset,setReset]=useState(false);const resetRef=useRef();
 useEffect(()=>{const change=()=>{setPath(route());window.scrollTo(0,0);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(saved));setStorageError(false);}catch{setStorageError(true);}},[saved]);
 useEffect(()=>{if(reset)resetRef.current.showModal();else resetRef.current?.close();},[reset]);
 const match=path.match(/^\/(teacher\/)?lesson\/(\d+)\/?$/);const lesson=match&&lessons.find(l=>l.id===match[2]);
 useEffect(()=>{document.title=path==='/project'?'O projekcie WIN4SMEs | Informatyka praktycznie':lesson?`${lesson.title} | Informatyka praktycznie`:'Informatyka praktycznie';},[path]);
 return <><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus();document.getElementById('main')?.scrollIntoView();}}>Przejdź do treści</a><Header/>{storageError&&<InfoNotice>Przeglądarka nie pozwala zapisać postępu. Ćwiczenia działają, ale odpowiedzi mogą zniknąć po odświeżeniu.</InfoNotice>}{path==='/'?<Home saved={saved}/>:path==='/teacher'?<TeacherIndex/>:path==='/project'?<ProjectPage base={base}/>:lesson?match[1]?<TeacherPlan lesson={lesson} base={base}/>:<Lesson key={lesson.id} lesson={lesson} saved={saved[lesson.id]} update={v=>setSaved(s=>({...s,[lesson.id]:v}))}/>:<main tabIndex={-1} id="main" className="empty-state"><h1>Nie ma takiej lekcji.</h1><a className="btn" href={`${base}#/`}>Wróć do listy lekcji</a></main>}<SiteFooter base={base} onReset={()=>setReset(true)}/><dialog ref={resetRef} className="reset-dialog" aria-labelledby="reset-title" onCancel={()=>setReset(false)}><h2 id="reset-title">Wyczyścić postęp?</h2><p>Usuniesz odpowiedzi i ukończone etapy wszystkich lekcji zapisane w tej przeglądarce.</p><div className="inline-actions"><button className="btn secondary" onClick={()=>setReset(false)}>Zostaw postęp</button><button className="btn" onClick={()=>{setSaved({});setReset(false);location.hash='/';}}>Wyczyść postęp</button></div></dialog></>;
}
createRoot(document.getElementById('root')).render(<App/>);
