import React,{Suspense,useEffect,useRef,useState} from 'react';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls} from '@react-three/drei';
import * as THREE from 'three';
import ComputerModel from './ComputerModel.jsx';
import {computerComponents} from '../../content/computer.js';

export function CameraController({controls,exploded,selected,reduced,action,isolated,parts=computerComponents}){
 const {camera,size,invalidate}=useThree();const tween=useRef(null);
 useEffect(()=>{
  if(!controls.current)return;const c=parts.find(x=>x.id===selected);const target=c?new THREE.Vector3(...(exploded?c.explodedPosition:c.position)):new THREE.Vector3(.15,.15,.3);
  const aspect=size.width/Math.max(size.height,1);const distance=c?(aspect<.85?7.5:5.5):exploded?Math.max(12,10.5/aspect):Math.max(9.7,6.8/aspect);
  if(c&&isolated){target.z+=.2;}const direction=new THREE.Vector3(.42,.25,1).normalize().multiplyScalar(c&&isolated?(c.focusDistance?c.focusDistance*Math.max(1,.85/aspect):(c.id==='case'?10:c.id==='motherboard'?8:c.id==='cpu'||c.id==='ssd'?3.5:5.5)):distance);const destination=target.clone().add(direction);
  tween.current={from:camera.position.clone(),to:destination,fromTarget:controls.current.target.clone(),target,elapsed:0};
  if(reduced){camera.position.copy(destination);controls.current.target.copy(target);controls.current.update();tween.current=null;}invalidate();
 },[exploded,selected,size.width,size.height,action?.reset,isolated,parts,reduced,camera,controls,invalidate]);
 useEffect(()=>{if(!controls.current||!action?.zoom)return;const offset=camera.position.clone().sub(controls.current.target);const factor=action.zoom>0?.82:1.22;offset.multiplyScalar(factor).clampLength(3.5,25);camera.position.copy(controls.current.target).add(offset);controls.current.update();tween.current=null;invalidate();},[action?.stamp]);
 useEffect(()=>{const c=controls.current;if(!c)return;const stop=()=>{tween.current=null;};c.addEventListener('start',stop);return()=>c.removeEventListener('start',stop);},[controls]);
 useFrame((_,dt)=>{const t=tween.current;if(!t||!controls.current)return;t.elapsed+=Math.min(dt,.05);const alpha=Math.min(t.elapsed/1.1,1);const e=alpha*alpha*(3-2*alpha);camera.position.lerpVectors(t.from,t.to,e);controls.current.target.lerpVectors(t.fromTarget,t.target,e);controls.current.update();if(alpha===1)tween.current=null;invalidate();});return null;
}
function SceneContent(props){const controls=useRef();const {gl}=useThree();useEffect(()=>{const lost=()=>props.onContextLost();gl.domElement.addEventListener('webglcontextlost',lost);return()=>gl.domElement.removeEventListener('webglcontextlost',lost);},[gl,props.onContextLost]);return <><color attach="background" args={['#edf0ed']}/><ambientLight intensity={1.35}/><hemisphereLight args={['#ffffff','#6c7e73',1.5]}/><directionalLight position={[3,7,6]} intensity={2.5} castShadow shadow-mapSize={[1024,1024]} shadow-camera-left={-5} shadow-camera-right={5} shadow-camera-top={5} shadow-camera-bottom={-5} shadow-bias={-.001}/><directionalLight position={[-4,2,-3]} intensity={1.6}/>{props.model?React.createElement(props.model,props):<ComputerModel {...props}/>}<mesh rotation={[-Math.PI/2,0,0]} position={[0,-2.85,0]} receiveShadow><planeGeometry args={[200,200]}/><shadowMaterial transparent opacity={.11}/></mesh><OrbitControls ref={controls} makeDefault enableDamping={!props.reduced} dampingFactor={.09} minDistance={3.5} maxDistance={25} minPolarAngle={.2} maxPolarAngle={Math.PI*.84} enablePan={false} zoomSpeed={.75} rotateSpeed={.65}/><CameraController controls={controls} {...props}/></>;}
function WebGLFallback(){return <div className="model-fallback">Twoja przeglądarka nie udostępnia WebGL. Skorzystaj z Listy elementów poniżej.</div>;}
export default function ComputerScene(props){const [supported]=useState(()=>{try{const canvas=document.createElement('canvas');const context=canvas.getContext('webgl2');if(!context)return false;context.getExtension('WEBGL_lose_context')?.loseContext();return true;}catch{return false;}});useEffect(()=>{if(!supported)props.onContextLost();},[supported]);if(!supported)return <WebGLFallback/>;return <Canvas aria-label={props.label||"Interaktywny model 3D komputera. Alternatywna obsługa dostępna przez Listę elementów."} role="img" shadows frameloop="demand" dpr={[1,1.5]} camera={{position:[4,3,10],fov:38,near:.1,far:100}} gl={{antialias:true,alpha:false,powerPreference:'default'}} fallback={<WebGLFallback onError={props.onContextLost}/>} onCreated={({gl})=>{props.onReady();}}><Suspense fallback={null}><SceneContent {...props}/></Suspense></Canvas>;}
