import React,{Component,Suspense,lazy,useEffect,useRef,useState} from 'react';
import {computerComponents,motherboardSlots,dataFlow,findChallenges} from '../../content/computer.js';
import {Icon} from '../icons.jsx';
import './computer.css';
const PhoneExplorer=lazy(()=>import('./PhoneExplorer.jsx'));
const ComputerScene=lazy(()=>import('./ComputerScene.jsx'));
export class ModelBoundary extends Component{state={failed:false};static getDerivedStateFromError(){return {failed:true};}componentDidCatch(){this.props.onError();}render(){return this.state.failed?<div className="model-fallback">Model 3D nie jest dostępny. Wszystkie informacje i zadanie są dostępne na Liście elementów.</div>:this.props.children;}}
function useReducedMotion(){const [reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const fn=()=>setReduced(q.matches);q.addEventListener('change',fn);return()=>q.removeEventListener('change',fn);},[]);return reduced;}
export function ComponentInfo({component,slot,onSlot,onBack}){return <aside className="component-info" aria-label={`Informacje: ${component.name}`}><button className="info-close" onClick={onBack} aria-label="Wróć do komputera"><Icon name="close" size={20}/></button><p className="component-kicker">{component.shortName}</p><h3>{component.name}</h3><p>{component.hook||component.description}</p><h4>W praktyce</h4><p>{component.practicalMeaning}</p>{component.example&&<p className="component-example">{component.example}</p>}{component.analogy&&<><h4>Pomocna analogia</h4><p>{component.analogy}</p></>}{component.id==='motherboard'&&<div className="socket-selector"><p>Wybierz gniazdo na modelu lub tutaj:</p><div>{motherboardSlots.map(s=><button key={s.id} aria-pressed={slot===s.id} onClick={()=>onSlot(s.id)}>{s.name}</button>)}</div>{slot&&<p role="status">{motherboardSlots.find(s=>s.id===slot)?.description}</p>}</div>}<button className="text-button" onClick={onBack}><Icon name="left" size={16}/>Wróć do komputera</button></aside>}
export function ComponentSelector({open,onToggle,onSelect,selected,challenge}){return <details className="component-list" open={open} onToggle={e=>onToggle(e.currentTarget.open)}><summary><Icon name="list" size={19}/>Lista elementów<span>Alternatywa dla modelu 3D</span><Icon name="down" size={17}/></summary><div>{computerComponents.map(c=><button key={c.id} aria-pressed={selected===c.id} onClick={()=>onSelect(c.id)}>{c.name}{c.shortName!==c.name&&<span>{c.shortName}</span>}</button>)}</div><p>{challenge?'Wybierz z listy poszukiwany element.':'Wybierz element, aby przeczytać opis. Listę można obsługiwać klawiszami Tab i Enter.'}</p></details>}
export function DataFlowAnimation({index,onNext,onClose}){const item=dataFlow[index];return <div className="data-flow-panel" aria-live="polite"><div><span className="component-kicker">Uruchamiasz grę · {index+1}/5</span><h3>{item.title}</h3><p>{item.text}</p></div><div className="flow-controls"><button className="btn secondary" onClick={onClose}>Wróć do modelu</button>{index<4&&<button className="btn" onClick={onNext}>Dalej <Icon name="right" size={17}/></button>}</div></div>}
export function FindComponentChallenge({value,onNext}){const index=Math.min(value.current||0,3);const current=findChallenges[index];return <div className="find-component"><div><span className="component-kicker">Gdzie to jest? · {index+1}/4</span><h3>{value.done?'Wszystkie cztery elementy odnalezione.':current.question}</h3><p>{value.done?'Potrafisz wskazać RAM, CPU, kartę graficzną i SSD. Przejdź do doboru komputera.':'Kliknij podzespół w rozłożonym komputerze. Możesz obracać widok i przybliżać.'}</p></div>{value.feedback&&<p className={`find-feedback ${value.success?'success':''}`} role="status">{value.success&&<Icon name="check" size={19}/>} {value.feedback}</p>}{value.success&&!value.done&&<button className="btn" onClick={onNext}>Następny element <Icon name="right" size={18}/></button>}</div>}
export function SmartphonePreview(){const [open,setOpen]=useState(false);return <div className="smartphone-preview"><button className="phone-launch" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Ukryj model telefonu':'Porównaj z iPhonem — rozłóż telefon 3D'} <Icon name="down" size={18}/></button>{open&&<Suspense fallback={<p role="status">Ładowanie modelu iPhone’a…</p>}><PhoneExplorer/></Suspense>}</div>}
export default function ComputerExplorer({data,value={},onChange}){
 const graded=data.type==='computerChallenge';const [mode,setMode]=useState(graded?'check':'discover');const challenge=mode==='check';const [practice,setPractice]=useState({});const quiz=graded?value:practice;const saveQuiz=graded?onChange:setPractice;const [exploded,setExploded]=useState(challenge||!!value.exploded);const [selected,setSelected]=useState(null);const [slot,setSlot]=useState(null);const [flow,setFlow]=useState(null);const [list,setList]=useState(false);const [ready,setReady]=useState(false);const [error,setError]=useState(false);const [presentation,setPresentation]=useState(false);const [cameraAction,setCameraAction]=useState({reset:0});const container=useRef();const presentationButton=useRef();const reduced=useReducedMotion();const active=flow!==null?dataFlow[flow].id:selected;
 function select(id){setSlot(null);if(challenge){if(quiz.success||quiz.done)return;const index=Math.min(quiz.current||0,3);const correct=id===findChallenges[index].id;setSelected(id);saveQuiz({...quiz,success:correct,feedback:correct?findChallenges[index].success:'To nie ten element. Spróbuj jeszcze raz.',done:correct&&index===3,solved:correct?[...new Set([...(quiz.solved||[]),id])]:quiz.solved||[]});}else{setFlow(null);setSelected(id);setExploded(true);onChange({...value,exploded:true,viewed:[...new Set([...(value.viewed||[]),id])]});}}
 function slotSelect(id){if(challenge)return;setSelected('motherboard');setExploded(true);setSlot(id);setFlow(null);}
 function back(){setSelected(null);setSlot(null);setFlow(null);setCameraAction(a=>({...a,reset:a.reset+1}));}
 function nextChallenge(){setSelected(null);saveQuiz({...quiz,current:Math.min((quiz.current||0)+1,3),success:false,feedback:'',done:false});}
 async function togglePresentation(){if(presentation){if(document.fullscreenElement)await document.exitFullscreen();setPresentation(false);presentationButton.current?.focus();}else{setPresentation(true);try{await container.current.requestFullscreen?.();}catch{/* CSS presentation mode remains available. */}}}
 useEffect(()=>{const key=e=>{if(e.key==='Escape'&&presentation){setPresentation(false);presentationButton.current?.focus();}};const fs=()=>{if(!document.fullscreenElement)setPresentation(false);};document.addEventListener('keydown',key);document.addEventListener('fullscreenchange',fs);return()=>{document.removeEventListener('keydown',key);document.removeEventListener('fullscreenchange',fs);};},[presentation]);
 useEffect(()=>{if(!presentation)return;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;};},[presentation]);
 const component=computerComponents.find(c=>c.id===active);const onError=()=>{setError(true);setReady(true);setList(true);};
 return <section ref={container} className={`computer-explorer ${presentation?'presentation-mode':''}`} aria-label={challenge?'Znajdź podzespoły komputera':'Poznaj wnętrze komputera'}>
 <div className="explorer-modes" role="group" aria-label="Tryb pracy z komputerem"><button aria-pressed={!challenge} onClick={()=>{setMode('discover');back();}}>Odkrywaj</button><button aria-pressed={challenge} onClick={()=>{setMode('check');setExploded(true);back();}}>Sprawdź się</button></div><p className="mode-description">{challenge?'Znajdź cztery podzespoły. Ich nazwy odsłonią się po poprawnej odpowiedzi.':'Kliknij dowolną część: zobaczysz ją z bliska, poznasz jej nazwę i dowiesz się, co robi.'}</p><div className="explorer-toolbar"><button className="btn" aria-pressed={exploded} onClick={()=>{setExploded(!exploded);back();onChange({...value,exploded:!exploded});}}>{exploded?'Złóż komputer':'Rozłóż komputer'}<Icon name={exploded?'reset':'app'} size={19}/></button><button ref={presentationButton} className="text-button" aria-pressed={presentation} onClick={togglePresentation}><Icon name="external" size={18}/>{presentation?'Zamknij prezentację':'Tryb prezentacji'}</button></div>
 {challenge&&<FindComponentChallenge value={quiz} onNext={nextChallenge}/>}
 <div className={`computer-viewport ${component&&!challenge?'has-info':''}`}>
 <ModelBoundary onError={onError}><Suspense fallback={<div className="model-loading" role="status">Przygotowuję model 3D…</div>}><ComputerScene isolated={!challenge&&flow===null&&!!component} exploded={exploded} selected={active} slot={slot} onSelect={select} onSlot={slotSelect} reduced={reduced} action={cameraAction} onReady={()=>setReady(true)} onContextLost={onError}/></Suspense></ModelBoundary>
 {!ready&&!error&&<div className="model-loading" role="status">Ładowanie wnętrza komputera…</div>}
 {component&&flow===null&&(!challenge||quiz.success)&&<div className="selected-part-name" aria-live="polite"><span>{challenge?'Dobrze! To jest:':'Odkrywasz'}</span><strong>{component.name}</strong></div>}
 <div className="model-view-controls" aria-label="Sterowanie widokiem"><button aria-label="Przybliż model" onClick={()=>setCameraAction(a=>({...a,zoom:1,stamp:Date.now()}))}>+</button><button aria-label="Oddal model" onClick={()=>setCameraAction(a=>({...a,zoom:-1,stamp:Date.now()}))}>−</button><button aria-label="Przywróć widok komputera" onClick={back}><Icon name="reset" size={18}/></button></div>
 {component&&!challenge&&flow===null&&<ComponentInfo component={component} slot={slot} onSlot={slotSelect} onBack={back}/>}
 </div>
 <p className="model-hint">Przeciągnij, aby obrócić. Scroll lub dwa palce: przybliżenie. Kliknij część, aby {challenge?'ją wskazać':'ją poznać'}.</p>
 {flow!==null&&<DataFlowAnimation index={flow} onNext={()=>setFlow(Math.min(flow+1,4))} onClose={back}/>}
 {!challenge&&flow===null&&<button className="text-button cooperation-button" onClick={()=>{setExploded(true);setSelected(null);setSlot(null);setFlow(0);}}>Zobacz, jak współpracują <Icon name="right" size={18}/></button>}
 <p className="model-disclaimer">To uproszczony model pokazujący podstawową rolę i położenie podzespołów. Układ w konkretnym komputerze może się różnić; to nie jest instrukcja montażu ani dokładny opis przepływu danych.</p>
 <ComponentSelector open={list||error} onToggle={setList} onSelect={select} selected={active} challenge={challenge}/>
 {!challenge&&<SmartphonePreview/>}
 </section>;
}
