import React,{useState,Suspense,lazy} from 'react';
const ComputerExplorer=lazy(()=>import('./computer/ComputerExplorer.jsx'));
import {Icon,fileIcon} from './icons.jsx';

export function FeedbackBox({children,ok=true}){return <div className={`feedback ${ok?'':'retry'}`} role="status"><Icon name={ok?'check':'book'}/><div>{children}</div></div>}
export function InfoCard({children}){return <div className="info-card">{children}</div>}
export function ProblemCard({children}){return <div className="problem-card">{children}</div>}
export function ChoiceQuestion({data,value={},onChange}){
 return <fieldset className="activity"><legend>{data.question}</legend><div className="choices">{data.options.map((o,i)=><button key={o} aria-pressed={value.selected===i} className={`choice ${value.selected===i?'selected':''}`} onClick={()=>onChange({selected:i,done:data.correct.includes(i)})}><span className="choice-letter">{String.fromCharCode(65+i)}</span><span>{o}</span>{value.selected===i&&<Icon name="check" size={20}/>}</button>)}</div>{value.selected!==undefined&&<FeedbackBox ok={value.done}>{value.done?data.explanation:`Spróbuj jeszcze raz. ${data.hint}`}</FeedbackBox>}</fieldset>
}
export function MultiChoiceQuestion({data,value={},onChange}){
 const selected=value.selected||[];const valid=selected.length>=(data.min||1)&&(!data.max||selected.length<=data.max);const checked=data.correct?selected.length===data.correct.length&&data.correct.every(x=>selected.includes(x)):valid;
 function toggle(i){const s=selected.includes(i)?selected.filter(x=>x!==i):[...selected,i];onChange({selected:s,submitted:false,done:false});}
 return <fieldset className="activity"><legend>{data.question}</legend><div className="choices">{data.options.map((o,i)=><label className={`choice ${selected.includes(i)?'selected':''}`} key={o}><input type="checkbox" checked={selected.includes(i)} onChange={()=>toggle(i)}/><span>{o}</span></label>)}</div>{data.max&&<p className="muted">Wybierz {data.min===data.max?`dokładnie ${data.max}`:`maksymalnie ${data.max}`} odpowiedzi. Zaznaczono: {selected.length}.</p>}<button className="btn" disabled={!valid} onClick={()=>onChange({...value,submitted:true,done:checked})}>Sprawdź wybór <Icon name="right" size={18}/></button>{value.submitted&&<FeedbackBox ok={checked}>{checked?data.explanation:'Spróbuj jeszcze raz. Zacznij od połączenia, właściwego urządzenia i prostych ustawień. Unikaj zmian całego systemu.'}</FeedbackBox>}</fieldset>
}
export function RevealCard({card}){return <details className="reveal-card"><summary><Icon name={card.icon||'file'} size={28}/><span><strong>{card.title}</strong><small>{card.short}</small></span><Icon name="down" size={18}/></summary><p>{card.text}</p></details>}
export function MatchingExercise({data,value={},onChange}){
 const answers=value.answers||{};
 function select(i,v){const a={...answers,[i]:Number(v)};onChange({answers:a,done:data.rows.every((r,j)=>r.correct.includes(a[j]))});}
 return <fieldset className="activity"><legend>{data.question}</legend><div className="matching">{data.rows.map((r,i)=><div className="match-row" key={r.label}><label htmlFor={`${data.id}-${i}`}>{r.label}</label><select id={`${data.id}-${i}`} value={answers[i]??''} onChange={e=>select(i,e.target.value)}><option value="" disabled>Wybierz odpowiedź</option>{data.options.map((o,j)=><option key={o} value={j}>{o}</option>)}</select>{answers[i]!==undefined&&<FeedbackBox ok={r.correct.includes(answers[i])}>{r.correct.includes(answers[i])?r.explanation:`Rozważ inny wybór. ${r.explanation}`}</FeedbackBox>}</div>)}</div></fieldset>
}
export function FileCard({name,...props}){return <button className="file-card" {...props}><Icon name={fileIcon(name)}/><span>{name}</span></button>}
export function DragDropExercise({data,value={},onChange}){
 const [picked,setPicked]=useState(null),[message,setMessage]=useState('');const placements=value.placements||{};
 function move(name,folder){if(!name||!data.files.some(([n])=>n===name))return;const correct=data.files.find(([n])=>n===name)[1];if(correct!==folder){setMessage(`${name}: spróbuj jeszcze raz. Spójrz na rozszerzenie pliku.`);return;}const p={...placements,[name]:folder};onChange({placements:p,done:data.files.every(([n,f])=>p[n]===f)});setPicked(null);setMessage(`${name} przeniesiono do folderu ${data.folders[folder]}.`);}
 return <div className="activity"><div className="file-tray" aria-label="Pliki do uporządkowania">{data.files.filter(([n])=>placements[n]===undefined).map(([n])=><FileCard key={n} name={n} draggable aria-pressed={picked===n} onDragStart={e=>{e.dataTransfer.setData('text/plain',n);setPicked(n);}} onClick={()=>setPicked(n)}/>)}</div><p className="muted" aria-live="polite">{picked?`Wybrano ${picked}. Teraz wybierz folder.`:`Przeniesiono ${Object.keys(placements).length} z ${data.files.length} plików.`}</p><div className="folder-grid">{data.folders.map((f,i)=><div className="folder-target" key={f} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();move(e.dataTransfer.getData('text/plain'),i);}}><button onClick={()=>move(picked,i)} aria-label={`Przenieś wybrany plik do folderu ${f}`}><Icon name="folder" size={32}/><strong>{f}</strong></button><ul>{data.files.filter(([n])=>placements[n]===i).map(([n])=><li key={n}><Icon name={fileIcon(n)} size={16}/>{n}</li>)}</ul></div>)}</div>{message&&<FeedbackBox ok={!message.includes('spróbuj')}>{message}</FeedbackBox>}{value.done&&<FeedbackBox>Wszystkie pliki są na swoim miejscu. Taką samą strukturę utworzysz za chwilę na komputerze.</FeedbackBox>}<button className="text-button" onClick={()=>{onChange({});setPicked(null);setMessage('Pliki wróciły do uporządkowania.');}}>Ułóż od nowa</button></div>
}
export function HardwareCard({item,selected,onClick}){return <div className={`hardware-card ${selected?'selected':''}`}><div className="hardware-art"><Icon name="laptop" size={112}/></div><h3>{item.name}</h3><dl><div><dt>RAM</dt><dd>{item.ram}</dd></div><div><dt>SSD</dt><dd>{item.ssd}</dd></div><div><dt>Procesor</dt><dd>{item.cpu}</dd></div><div><dt>Grafika</dt><dd>{item.gpu}</dd></div></dl><strong className="price">{item.price}</strong><button className={selected?'btn':'btn secondary'} aria-pressed={selected} onClick={onClick}>{selected?'Wybrano':'Wybieram'}<Icon name={selected?'check':'right'} size={18}/></button></div>}
export function DevicePort({port,onClick,selected}){return <button className={`device-port ${selected?'selected':''}`} aria-pressed={selected} onClick={onClick}><span className={`port-shape ${port.shape}`} aria-hidden="true"><i/></span><span>{port.name}</span></button>}
function Ports({data,value={},onChange}){const port=data.ports[value.selected??0];return <div className="activity"><div className="laptop-edge">{data.ports.map((p,i)=><DevicePort key={p.name} port={p} selected={value.selected===i} onClick={()=>onChange({selected:i})}/>)}</div><InfoCard><div className="port-detail"><span className={`port-shape plug ${port.shape}`} aria-hidden="true"><i/></span><div><h3>{port.name}</h3><p>{port.text}</p><small>Uproszczony rysunek czoła wtyczki, bez zachowania skali.</small></div></div></InfoCard></div>}
export function DiagnosticScenario({data,value={},onChange}){return <div className="scenarios">{data.cases.map((c,i)=><details className="scenario" key={c.title} open={i===0?undefined:undefined}><summary><Icon name={c.icon}/><span>{c.title}</span><span className="scenario-status">{value[i]?.done?'Gotowe':'3 kroki'}</span><Icon name="down" size={18}/></summary><MultiChoiceQuestion data={{...c,id:`${data.id}-${i}`,question:'Wybierz trzy pierwsze działania.',min:3,max:3}} value={value[i]} onChange={v=>{const all={...value,[i]:v};all.done=data.cases.every((_,j)=>all[j]?.done);onChange(all);}}/></details>)}</div>}
export function MicroVideo({data,base}){return <details className="micro-video"><summary><Icon name="play"/><span>{data.title}<small>{data.duration} · {data.file?'Film':'Film w przygotowaniu'}</small></span><Icon name="down" size={18}/></summary>{data.file?<><video controls preload="metadata" poster={data.poster?base+data.poster:undefined}>{<source src={base+data.file}/>} {data.captions&&<track kind="captions" src={base+data.captions} srcLang="pl" label="Polski" default/>}</video>{data.transcript&&<details><summary>Transkrypcja</summary><p>{data.transcript}</p></details>}</>:<p>Nagranie pojawi się później. Wszystkie informacje potrzebne do ćwiczenia są dostępne w tej lekcji.</p>}</details>}
export function DownloadMaterial({data,base}){return <div className="download-material"><Icon name="zip" size={40}/><div><a className="btn" download href={base+data.file}>{data.label}<Icon name="download" size={19}/></a><p>{data.description}</p></div></div>}
function Flow({data,value={},onChange}){const step=value.step??0;return <div className="flow activity"><ol>{data.nodes.map((n,i)=><li key={n.title} className={i<=step?'revealed':'pending'}><span className="step-number">{i+1}</span>{i<=step?<div><strong>{n.title}</strong><p>{n.text}</p></div>:<span>Kolejny krok</span>}</li>)}</ol><div className="inline-actions"><button className="btn" disabled={step===data.nodes.length-1} onClick={()=>onChange({step:step+1})}>{step===data.nodes.length-1?'Cały schemat odkryty':'Odkryj kolejny krok'}<Icon name="right" size={18}/></button>{step>0&&<button className="text-button" onClick={()=>onChange({step:0})}>Od początku</button>}</div></div>}
function TextAnswer({data,value={},onChange}){const [error,setError]=useState('');const text=value.text||'';function submit(e){e.preventDefault();if(data.mode==='filename'){if(!text.toLowerCase().endsWith(data.extension)||/[<>:"/\\|?*\u0000-\u001f]/.test(text)||text.replace(data.extension,'').trim().length<4){setError(`Wpisz opisową nazwę zakończoną ${data.extension}. Nie używaj znaków takich jak / : * ?.`);return;}}else if(text.trim().length<(data.minLength||3)){setError('Dodaj krótkie uzasadnienie, nie tylko jedno słowo.');return;}setError('');onChange({...value,done:true});}
return <form className="activity" onSubmit={submit}><label className="question" htmlFor={data.id}>{data.question}</label><input id={data.id} type="text" autoComplete="off" maxLength={500} value={text} placeholder={data.placeholder} onChange={e=>{onChange({text:e.target.value,done:false});setError('');}}/><button className="btn" type="submit">Porównaj odpowiedź <Icon name="right" size={18}/></button>{error&&<FeedbackBox ok={false}>{error}</FeedbackBox>}{value.done&&<FeedbackBox>{data.explanation}</FeedbackBox>}</form>}
function Sequence({data,value={},onChange}){const order=value.order||[];return <div className="activity"><h3>{data.question}</h3><div className="choices">{data.options.map((o,i)=><button className={`choice ${order.includes(i)?'selected':''}`} key={o} onClick={()=>onChange({order:order.includes(i)?order.filter(x=>x!==i):[...order,i],done:false})}><span className="choice-letter">{order.includes(i)?order.indexOf(i)+1:'+'}</span>{o}</button>)}</div><button className="btn" disabled={order.length!==data.correct.length} onClick={()=>onChange({...value,submitted:true,done:order.every((n,i)=>n===data.correct[i])})}>Sprawdź kolejność</button>{value.submitted&&<FeedbackBox ok={value.done}>{value.done?data.explanation:'Spróbuj jeszcze raz. Najpierw sprawdź zasilanie, potem połączenie, a następnie właściwe urządzenie. Kliknij zaznaczone kroki, aby je odznaczyć.'}</FeedbackBox>}</div>}
function AppNeeds({data,value={},onChange}){const selected=value.selected||[];return <div className="activity"><label className="question" htmlFor={data.id}>{data.question}</label><select id={data.id} value={value.category||''} onChange={e=>onChange({category:e.target.value,selected:[],done:false})}><option value="" disabled>Wybierz kategorię</option>{data.categories.map(c=><option key={c}>{c}</option>)}</select>{value.category&&<><fieldset><legend>Co może być potrzebne? Wybierz co najmniej jedną możliwość.</legend><div className="check-chips">{data.options.map(o=><label className={selected.includes(o)?'selected':''} key={o}><input type="checkbox" checked={selected.includes(o)} onChange={()=>onChange({...value,selected:selected.includes(o)?selected.filter(x=>x!==o):[...selected,o],done:false})}/>{o}</label>)}</div></fieldset><label htmlFor={`${data.id}-reason`}>Do jakiej konkretnej funkcji?</label><input id={`${data.id}-reason`} maxLength={400} value={value.reason||''} onChange={e=>onChange({...value,reason:e.target.value,done:false})} placeholder="Np. wysłanie zdjęcia w wiadomości"/><button className="btn" disabled={!selected.length||!(value.reason||'').trim()} onClick={()=>onChange({...value,done:true})}>Porównaj z przykładami</button></>}{value.done&&<FeedbackBox><strong>To zależy od konkretnej funkcji aplikacji.</strong><ul>{selected.map(s=><li key={s}><b>{s}:</b> {data.hints[s]}</li>)}</ul>Porównaj te przykłady ze swoim uzasadnieniem. Strona nie ocenia go automatycznie.</FeedbackBox>}</div>}
export function ExitTicket({children}){return <div className="exit-ticket">{children}</div>}
export function Activity({data,value,onChange,base}){
 switch(data.type){
 case 'computerExplorer':
 case 'computerChallenge':return <Suspense fallback={<p role="status">Przygotowuję interaktywny model komputera…</p>}><ComputerExplorer data={data} value={value} onChange={onChange}/></Suspense>;
 case 'choice':return <ChoiceQuestion data={data} value={value} onChange={onChange}/>;
 case 'multi':return <MultiChoiceQuestion data={data} value={value} onChange={onChange}/>;
 case 'reveal':return <div className="reveal-grid">{data.cards.map(c=><RevealCard key={c.title} card={c}/>)}</div>;
 case 'matching':return <MatchingExercise data={data} value={value} onChange={onChange}/>;
 case 'sort':return <DragDropExercise data={data} value={value} onChange={onChange}/>;
 case 'hardwareReference':return <aside className="hardware-reference" aria-label="Porównanie komputerów A, B i C"><h3>{data.question}</h3><div>{data.items.map(h=><section key={h.name}><h4>{h.name}<span>{h.price}</span></h4><dl>{[['Procesor',h.cpu],['RAM',h.ram],['SSD',h.ssd],['Grafika',h.gpu]].map(([label,v])=><div key={label}><dt>{label}</dt><dd>{v}</dd></div>)}</dl></section>)}</div><p>Te same fikcyjne konfiguracje co na początku lekcji.</p></aside>;
 case 'hardware':return <div className="activity"><p className="muted">Fikcyjne konfiguracje i ceny do ćwiczenia. Opisy CPU i GPU są celowo uproszczone.</p><div className="hardware-grid">{data.items.map((h,i)=><HardwareCard key={h.name} item={h} selected={value?.selected===i} onClick={()=>onChange({selected:i,done:true})}/>)}</div>{value?.done&&<FeedbackBox>{data.explanation}</FeedbackBox>}</div>;
 case 'ports':return <Ports data={data} value={value} onChange={onChange}/>;
 case 'scenarios':return <DiagnosticScenario data={data} value={value} onChange={onChange}/>;
 case 'video':return <MicroVideo data={data} base={base}/>;
 case 'download':return <DownloadMaterial data={data} base={base}/>;
 case 'flow':return <Flow data={data} value={value} onChange={onChange}/>;
 case 'text':return <TextAnswer data={data} value={value} onChange={onChange}/>;
 case 'sequence':return <Sequence data={data} value={value} onChange={onChange}/>;
 case 'appNeeds':return <AppNeeds data={data} value={value} onChange={onChange}/>;
 case 'fileCloud':return <div className="file-cloud" aria-label="Przykładowy nieuporządkowany folder">{data.files.map(n=><span key={n}><Icon name={fileIcon(n)} size={22}/>{n}</span>)}</div>;
 case 'filename':return <div className="filename-demo"><div><span>{data.name}</span><strong>{data.extension}</strong></div><p>Nazwa opisuje zawartość. <b>Rozszerzenie</b> wskazuje format. Zmiana samej końcówki nie konwertuje pliku.</p></div>;
 case 'connection':return <div className="connection-scene"><div><Icon name={data.from==='Laptop'?'laptop':'app'} size={80}/><strong>{data.from}</strong></div><span className="cable">{data.cable}<Icon name="right" size={34}/></span><div><Icon name="projector" size={80}/><strong>{data.to}</strong></div><p>{data.status}</p></div>;
 case 'diagram':return <figure className="computer-diagram"><div>{data.nodes.map((n,i)=><React.Fragment key={n}><span><Icon name={['cpu','memory','drive','gpu'][i]} size={30}/>{n}</span>{i<data.nodes.length-1&&<b aria-label="współpraca">↔</b>}</React.Fragment>)}</div><figcaption>{data.caption}</figcaption></figure>;
 case 'phone':return <div className="phone-scene"><div className="phone-functions">{data.items.slice(0,3).map((n,i)=><span key={n}><Icon name={['location','headphones','nfc'][i]}/>{n}</span>)}</div><Icon name="phone" size={150}/><div className="phone-functions">{data.items.slice(3).map((n,i)=><span key={n}><Icon name={['bluetooth','wifi','camera'][i]}/>{n}</span>)}</div></div>;
 case 'checklist':return <div className="activity checklist"><fieldset><legend>Wykonane kroki</legend>{data.items.map((s,i)=><label key={s}><input type="checkbox" checked={!!value?.checks?.[i]} onChange={e=>{const checks={...value?.checks,[i]:e.target.checked};onChange({checks,done:data.items.every((_,j)=>checks[j])});}}/>{s}</label>)}</fieldset>{value?.done&&<FeedbackBox>{data.explanation}</FeedbackBox>}</div>;
 default:return <FeedbackBox ok={false}>Nie udało się wyświetlić tego zadania. Wróć do listy lekcji i spróbuj ponownie.</FeedbackBox>;
 }
}
