import React from 'react';
import {dentalSchema,examplePatients} from '../content/dental-simulator.js';

const types={integer:'Liczba całkowita',text:'Tekst',datetime:'Data i godzina'};
export function TableInstructions({name}) {
 const schema=dentalSchema[name];
 return <div className="dental-instructions">
  <p><b>{name==='Pacjenci'?'Krok 1':'Krok 2'}. Ustaw pola tabeli {name}</b></p>
  <ol>{Object.entries(schema.fields).map(([field,type])=><li key={field}>Przy <b>{field}</b> otwórz listę „Wybierz typ” i kliknij <b>{types[type]}</b>.</li>)}<li>Na liście <b>Klucz główny</b> wybierz <b>{schema.key}</b>.</li><li>Kliknij <b>Utwórz tabelę {name}</b>.</li></ol>
  <p>Sprawdź: przy nazwie tabeli pojawi się „utworzona”, a jej pola staną się nieaktywne. {name==='Pacjenci'?'Następnie utwórz tabelę Wizyty.':'Następnie przejdź do „Relacja między tabelami” poniżej.'}</p>
 </div>;
}
export function RelationInstructions(){return <aside className="dental-assignment"><h4>Krok 3. Połącz tabele</h4><ol><li>W polu <b>Klucz obcy w Wizyty</b> wybierz <b>id_pacjenta</b>.</li><li>W polu <b>Wskazuje pole w Pacjenci</b> również wybierz <b>id_pacjenta</b>.</li><li>Kliknij <b>Połącz tabele</b>. Powinien pojawić się komunikat „Relacja gotowa”.</li><li>Kliknij <b>Przejdź do danych</b> pod relacją lub zakładkę <b>2. Dane</b>.</li></ol><p>Nie wybieraj id_wizyty: łączysz wizytę z osobą, a nie z numerem innej wizyty.</p></aside>;}
export function PatientInstructions(){return <aside className="dental-assignment"><h4>Krok 4. Wpisz dokładnie tych trzech pacjentów</h4><p>Wypełniaj formularz „Nowy pacjent” poniżej. Jeden wiersz wzoru to jedna osoba. Wszystkie osoby są fikcyjne.</p><div className="dental-table-scroll" role="region" aria-label="Wzór danych pacjentów" tabIndex={0}><table><caption>Dane do przepisania</caption><thead><tr><th scope="col">ID pacjenta</th><th scope="col">Imię</th><th scope="col">Nazwisko</th></tr></thead><tbody>{examplePatients.map(p=><tr key={p.id_pacjenta}><td>{p.id_pacjenta}</td><td>{p.imie}</td><td>{p.nazwisko}</td></tr>)}</tbody></table></div><ol>{examplePatients.map(p=><li key={p.id_pacjenta}>Wpisz <b>{p.id_pacjenta}</b> w „ID pacjenta”, <b>{p.imie}</b> w „Imię” i <b>{p.nazwisko}</b> w „Nazwisko”. Kliknij <b>Dodaj pacjenta</b>. Sprawdź, czy osoba pojawiła się w tabeli „Pacjenci” pod formularzem.</li>)}</ol><p>Po każdym dodaniu formularz się wyczyści — to prawidłowe. Wpisz wtedy następną osobę. Zachowaj wielkie litery i polskie znaki, np. „ł” w „Przykładowy”. Po ostatniej osobie tabela ma zawierać 3 rekordy.</p><p>Jeśli pomylisz imię lub nazwisko, kliknij <b>Popraw</b> w wierszu tej osoby, zmień tekst w formularzu nad tabelą i kliknij <b>Zapisz pacjenta</b>. Numeru ID nie można zmienić: jeśli wpiszesz inny, dodaj brakującą osobę z właściwym ID. Dodatkowy rekord nie blokuje ukończenia zadania.</p></aside>;}
export function VisitInstructions(){return <div className="dental-instructions"><h4>Krok 6. Dodaj piątą wizytę formularzem poniżej</h4><ol><li>W „ID wizyty” wpisz <b>5</b>.</li><li>W „ID pacjenta wizyty” wpisz <b>1</b> — to Ada Testowa.</li><li>W „Data wizyty” wybierz <b>23 września 2026 r.</b> w kalendarzu lub wpisz datę w formacie pokazanym w polu, np. <b>23.09.2026</b>.</li><li>W „Godzina wizyty” ustaw <b>10:00</b> (jeśli widzisz AM/PM, wybierz 10:00 AM).</li><li>W „Cel wizyty” wpisz <b>kontrola</b>, małymi literami.</li><li>Kliknij <b>Dodaj wizytę</b> tylko raz.</li></ol><p>Sprawdź tabelę „Wizyty”: powinno być 5 rekordów, w tym wiersz <b>5 | 1 | 2026-09-23 10:00 | kontrola</b>. Data w tabeli ma kolejność rok–miesiąc–dzień, nawet jeśli formularz pokazuje ją inaczej.</p><p>Pomyłkę popraw przez <b>Popraw</b> w wierszu wizyty, zmianę pól w formularzu i <b>Zapisz wizytę</b>. Gdy cztery zadania nad symulatorem mają ✓, przewiń pod cały symulator i kliknij <b>Przejdź dalej</b>. To zatwierdza etap „Zrób” i otwiera „Zastosuj”.</p></div>;}
export function SearchInstructions(){return <aside className="dental-assignment"><h4>Krok 7. Znajdź plan dnia i wizyty Ady</h4><p>Używasz tej samej bazy co w etapie „Zrób”. Nie twórz tabel ponownie.</p><ol><li>W formularzu „Wyszukaj wizyty” ustaw <b>Filtr → Dzień wizyty</b>.</li><li>W „Dzień wyszukiwania” wybierz <b>21 września 2026 r.</b></li><li>Ustaw <b>Kolejność → Od najwcześniejszej</b> i kliknij <b>Wyszukaj</b>.</li><li>Sprawdź wynik: <b>09:00 — Ada Testowa; 09:30 — Jan Przykładowy; 10:00 — Ewa Modelowa</b>. Pod wynikiem zadanie „Plan dnia 21.09.2026” otrzyma ✓.</li><li>W tym samym formularzu zmień <b>Filtr → Pacjent</b>. Pojawi się lista „Wybierz pacjenta”. Wybierz <b>1 — Ada Testowa</b>.</li><li>Pozostaw <b>Od najwcześniejszej</b> i ponownie kliknij <b>Wyszukaj</b>.</li><li>Sprawdź trzy wizyty Ady: <b>21.09.2026 09:00; 22.09.2026 11:00; 23.09.2026 10:00</b>. Zadanie „Wizyty Ady” otrzyma ✓.</li><li>Odpowiedz na dwa pytania pod całym symulatorem i kliknij <b>Przejdź dalej</b>, aby zatwierdzić etap „Zastosuj”.</li></ol><p>Podane wyniki dotyczą pięciu wizyt z zadania. Jeśli nie widzisz ✓, wróć do „2. Dane”, sprawdź wymagane rekordy i ponownie wykonaj oba wyszukiwania. Dodatkowe wizyty mogą rozszerzyć wyniki.</p></aside>;}
