import React,{useState} from 'react';
import {dentalSchema,dentalState,dentalProgress,createDentalTable,connectDentalTables,saveDentalPatient,saveDentalVisit,loadExampleVisits,runDentalQuery,queryDentalRows,dentalQuerySQL} from '../content/dental-simulator.js';
import './dental-simulator.css';
import {TableInstructions,RelationInstructions,PatientInstructions,VisitInstructions,SearchInstructions} from './DentalInstructions.jsx';

function DataTable({caption,columns,rows,edit}) {
 return <div className="dental-table-scroll" role="region" aria-label={caption} tabIndex={0}><table><caption>{caption} · {rows.length} {rows.length===1?'rekord':'rekordów'}</caption><thead><tr>{columns.map(([key,label])=><th scope="col" key={key}>{label}</th>)}{edit&&<th scope="col">Działanie</th>}</tr></thead><tbody>{rows.length?rows.map((row,i)=><tr key={i}>{columns.map(([key])=><td key={key}>{row[key]}</td>)}{edit&&<td><button type="button" className="text-button" onClick={()=>edit(row)} aria-label={`Popraw ${caption==='Pacjenci'?'pacjenta':'wizytę'} ${row[columns[0][0]]}`}>Popraw</button></td>}</tr>):<tr><td colSpan={columns.length+(edit?1:0)}>Tabela jest pusta.</td></tr>}</tbody></table></div>;
}
const patientColumns=[['id_pacjenta','id_pacjenta'],['imie','imie'],['nazwisko','nazwisko']];
const visitColumns=[['id_wizyty','id_wizyty'],['id_pacjenta','id_pacjenta'],['termin','termin'],['cel','cel']];
const emptyPatient={id_pacjenta:'',imie:'',nazwisko:''};
const emptyVisit={id_wizyty:'',id_pacjenta:'',day:'',time:'',cel:''};

export default function DentalSimulator({data,value,onChange}) {
 const s=dentalState(value),progress=dentalProgress(s);
 const [tab,setTab]=useState(data.mode==='query'?'search':'design');
 const [message,setMessage]=useState(null),[reset,setReset]=useState(false);
 const patient=s.drafts.patient||emptyPatient,visit=s.drafts.visit||emptyVisit;
 function draft(key,v){onChange({...s,drafts:{...s.drafts,[key]:v}});}
 function act(fn,success,scope){try{onChange(fn());setMessage({ok:true,text:success,scope});return true;}catch(e){setMessage({ok:false,text:e.message,scope});return false;}}
 function selectTab(next){setTab(next);setMessage(null);setReset(false);}
 function savePatient(e){e.preventDefault();act(()=>{const next=saveDentalPatient(s,patient,!!patient.editing);return {...next,drafts:{...next.drafts,patient:emptyPatient}};},'Rekord pacjenta zapisany. Sprawdź go w tabeli.','patient');}
 function saveVisit(e){e.preventDefault();act(()=>{const next=saveDentalVisit(s,{...visit,termin:`${visit.day} ${visit.time}`},!!visit.editing);return {...next,drafts:{...next.drafts,visit:emptyVisit}};},'Rekord wizyty zapisany. Pacjent i termin są powiązane.','visit');}
 const tasks=[['tables','Utwórz dwie tabele'],['relation','Połącz klucze'],['patients','Wpisz 3 pacjentów'],['visits','Dodaj 5 wizyt']];
 return <section className="dental-simulator" aria-label="Symulator bazy gabinetu">
  <header className="dental-heading"><p className="eyebrow">Twoja baza · gabinet</p><h3>Mały gabinet, uporządkowane dane.</h3><p>Wszystko wykonujesz tutaj. To edukacyjny model bazy z formularzami, tabelami i wyszukiwaniem.</p></header>
  <ol className="dental-progress" aria-label="Zadania w symulatorze">{tasks.map(([key,label])=><li key={key} className={progress[key]?'is-done':''}><span aria-hidden="true">{progress[key]?'✓':'○'}</span>{label}<span className="sr-only">{progress[key]?' — gotowe':' — do wykonania'}</span></li>)}</ol>
  <div className="dental-tabs" role="group" aria-label="Widok bazy">{[['design','1. Projekt'],['records','2. Dane'],['search','3. Wyszukiwanie']].map(([key,label])=><button type="button" key={key} aria-pressed={tab===key} onClick={()=>selectTab(key)}>{label}</button>)}</div>
  {message&&!message.scope&&<div className={`dental-message ${message.ok?'':'is-error'}`} role={message.ok?'status':'alert'}>{message.text}</div>}
  {tab==='design'&&<div className="dental-panel">
   <p>Zacznij od tabeli <b>Pacjenci</b>, potem utwórz <b>Wizyty</b>. Nazw pól nie wpisujesz — są już przygotowane. Klikaj listy przy polach według instrukcji nad formularzami. Po poprawnym utworzeniu tabela się zablokuje; nie twórz jej ponownie.</p>
   <div className="dental-design-grid">{Object.entries(dentalSchema).map(([name,schema])=>{const design=s.drafts[name]||{fields:{},key:''};return <form key={name} onSubmit={e=>{e.preventDefault();act(()=>createDentalTable(s,name,design),`Tabela ${name} utworzona. Teraz możesz zapisać w niej rekordy.`);}}><TableInstructions name={name}/><fieldset disabled={s.tables[name]}><legend>Tabela {name}{s.tables[name]?' · utworzona':''}</legend>{Object.keys(schema.fields).map(field=><label key={field}>{field}<select aria-label={`Typ ${name}.${field}`} value={design.fields[field]||''} onChange={e=>draft(name,{...design,fields:{...design.fields,[field]:e.target.value}})}><option value="">Wybierz typ</option><option value="integer">Liczba całkowita</option><option value="text">Tekst</option><option value="datetime">Data i godzina</option></select></label>)}<label>Klucz główny<select aria-label={`Klucz główny ${name}`} value={design.key} onChange={e=>draft(name,{...design,key:e.target.value})}><option value="">Wybierz pole</option>{Object.keys(schema.fields).map(field=><option key={field}>{field}</option>)}</select></label><button className="btn" type="submit">{s.tables[name]?'Tabela gotowa':`Utwórz tabelę ${name}`}</button></fieldset></form>;})}</div>
   <RelationInstructions/><form className="dental-relation" onSubmit={e=>{e.preventDefault();act(()=>connectDentalTables(s,s.drafts.source,s.drafts.target),'Relacja gotowa: jeden pacjent może mieć wiele wizyt.');}}><fieldset disabled={s.relation}><legend>Relacja między tabelami</legend><div className="dental-form-grid"><label>Klucz obcy w Wizyty<select aria-label="Klucz obcy w Wizyty" value={s.drafts.source||''} onChange={e=>draft('source',e.target.value)}><option value="">Wybierz pole</option>{Object.keys(dentalSchema.Wizyty.fields).map(f=><option key={f}>{f}</option>)}</select></label><label>Wskazuje pole w Pacjenci<select aria-label="Wskazuje pole w Pacjenci" value={s.drafts.target||''} onChange={e=>draft('target',e.target.value)}><option value="">Wybierz pole</option>{Object.keys(dentalSchema.Pacjenci.fields).map(f=><option key={f}>{f}</option>)}</select></label></div><button className="btn secondary" type="submit" disabled={!progress.tables}>{s.relation?'Relacja gotowa':'Połącz tabele'}</button>{!progress.tables&&<p>Najpierw utwórz obie tabele.</p>}</fieldset></form>
   {s.relation&&<p className="dental-relation-result">Pacjenci.id_pacjenta <strong>1 → wiele</strong> Wizyty.id_pacjenta</p>}
   <button type="button" className="btn secondary" onClick={()=>selectTab('records')}>Przejdź do danych</button>
  </div>}
  {tab==='records'&&<div className="dental-panel">
   <PatientInstructions/>
   <form onSubmit={savePatient}><fieldset disabled={!s.tables.Pacjenci}><legend>{patient.editing?'Popraw pacjenta':'Nowy pacjent'}</legend><div className="dental-form-grid"><label>ID pacjenta<input inputMode="numeric" value={patient.id_pacjenta} disabled={patient.editing} onChange={e=>draft('patient',{...patient,id_pacjenta:e.target.value})}/></label><label>Imię<input maxLength={60} value={patient.imie} onChange={e=>draft('patient',{...patient,imie:e.target.value})}/></label><label>Nazwisko<input maxLength={60} value={patient.nazwisko} onChange={e=>draft('patient',{...patient,nazwisko:e.target.value})}/></label></div><button className="btn" type="submit">{patient.editing?'Zapisz pacjenta':'Dodaj pacjenta'}</button>{patient.editing&&<button className="text-button" type="button" onClick={()=>draft('patient',emptyPatient)}>Anuluj poprawianie pacjenta</button>}<DentalMessage message={message} scope="patient"/></fieldset></form>
   {!s.tables.Pacjenci&&<p>Utwórz tabelę Pacjenci w zakładce Projekt.</p>}
   <DataTable caption="Pacjenci" columns={patientColumns} rows={s.patients} edit={p=>{draft('patient',{...p,editing:true});setMessage({ok:true,text:'Rekord otwarty w formularzu nad tabelą. ID pozostaje ten sam.'});}}/>
   <aside className="dental-assignment"><h4>Krok 5. Wczytaj pierwsze cztery wizyty</h4><p>Gdy tabela „Pacjenci” zawiera trzy osoby z wzoru, kliknij poniżej <b>Wczytaj 4 przykładowe wizyty</b>. Przewiń do tabeli „Wizyty” i sprawdź, czy są wiersze o ID 1, 2, 3 i 4. Tych wizyt nie przepisujesz ręcznie.</p><p>Jeśli przycisk jest nieaktywny, sprawdź relację w „1. Projekt” oraz ID, imiona i nazwiska w „2. Dane”. Wszystkie muszą odpowiadać wzorowi.</p><button className="btn secondary" type="button" disabled={!s.relation||!progress.patients} onClick={()=>act(()=>loadExampleVisits(s),'Cztery przykładowe wizyty są w tabeli. Teraz samodzielnie dodaj wizytę 5.','seed')}>Wczytaj 4 przykładowe wizyty</button><DentalMessage message={message} scope="seed"/></aside>
   <VisitInstructions/><form onSubmit={saveVisit}><fieldset disabled={!s.relation}><legend>{visit.editing?'Popraw wizytę':'Nowa wizyta'}</legend><div className="dental-form-grid"><label>ID wizyty<input inputMode="numeric" value={visit.id_wizyty} disabled={visit.editing} onChange={e=>draft('visit',{...visit,id_wizyty:e.target.value})}/></label><label>ID pacjenta wizyty<input inputMode="numeric" value={visit.id_pacjenta} onChange={e=>draft('visit',{...visit,id_pacjenta:e.target.value})}/></label><label>Data wizyty<input type="date" value={visit.day} onChange={e=>draft('visit',{...visit,day:e.target.value})}/></label><label>Godzina wizyty<input type="time" value={visit.time} onChange={e=>draft('visit',{...visit,time:e.target.value})}/></label><label>Cel wizyty<input maxLength={60} value={visit.cel} onChange={e=>draft('visit',{...visit,cel:e.target.value})}/></label></div><button className="btn" type="submit">{visit.editing?'Zapisz wizytę':'Dodaj wizytę'}</button>{visit.editing&&<button className="text-button" type="button" onClick={()=>draft('visit',emptyVisit)}>Anuluj poprawianie wizyty</button>}<DentalMessage message={message} scope="visit"/></fieldset></form>
   {!s.relation&&<p>Najpierw połącz tabele w zakładce Projekt.</p>}
   <DataTable caption="Wizyty" columns={visitColumns} rows={s.visits} edit={v=>{const [day,time]=v.termin.split(' ');draft('visit',{...v,day,time,editing:true});setMessage({ok:true,text:'Wizyta otwarta w formularzu nad tabelą. Popraw dane i zapisz.'});}}/>
   {progress.create&&<p className="dental-message" role="status">Baza przygotowana poprawnie. Możesz zatwierdzić etap „Zrób” i przejść do wyszukiwania.</p>}
   <button type="button" className="btn secondary" onClick={()=>selectTab('search')}>Przejdź do wyszukiwania</button>
  </div>}
  {tab==='search'&&<div className="dental-panel">
   <SearchInstructions/>
   <form onSubmit={e=>{e.preventDefault();act(()=>runDentalQuery(s,s.query),'Wyszukiwanie wykonane. Sprawdź wynik poniżej.','search');}}><fieldset disabled={!s.relation}><legend>Wyszukaj wizyty</legend><div className="dental-form-grid"><label>Filtr<select aria-label="Filtr" value={s.query.kind} onChange={e=>onChange({...s,query:{...s.query,kind:e.target.value},executed:null})}><option value="day">Dzień wizyty</option><option value="patient">Pacjent</option></select></label>{s.query.kind==='day'?<label>Dzień wyszukiwania<input type="date" value={s.query.day} onChange={e=>onChange({...s,query:{...s.query,day:e.target.value},executed:null})}/></label>:<label>Wybierz pacjenta<select aria-label="Wybierz pacjenta" value={s.query.patient} onChange={e=>onChange({...s,query:{...s.query,patient:e.target.value},executed:null})}><option value="">Wybierz osobę</option>{s.patients.map(p=><option value={p.id_pacjenta} key={p.id_pacjenta}>{p.id_pacjenta} — {p.imie} {p.nazwisko}</option>)}</select></label>}<label>Kolejność<select aria-label="Kolejność" value={s.query.order} onChange={e=>onChange({...s,query:{...s.query,order:e.target.value},executed:null})}><option value="asc">Od najwcześniejszej</option><option value="desc">Od najpóźniejszej</option></select></label></div><button className="btn" type="submit">Wyszukaj</button><DentalMessage message={message} scope="search"/></fieldset></form>
   {!s.relation&&<p>Ta sama baza jest dostępna w etapie „Zrób”. Możesz też przygotować ją tutaj, zaczynając od zakładki Projekt.</p>}
   {s.executed&&<><DataTable caption="Wynik wyszukiwania" columns={[['termin','Termin'],['imie','Imię'],['nazwisko','Nazwisko'],['cel','Cel']]} rows={queryDentalRows(s,s.executed)}/>{!queryDentalRows(s,s.executed).length&&<p>Brak wizyt spełniających warunek. Zmień filtr lub sprawdź dane.</p>}<details className="dental-sql"><summary>Jak wyglądałoby to zapytanie w SQL?</summary><p>Formularz symuluje połączenie tabel (JOIN), filtrowanie (WHERE) i sortowanie (ORDER BY). To zapis poglądowy; nie musisz wpisywać kodu.</p><pre><code>{dentalQuerySQL(s.executed)}</code></pre></details></>}
   <ul className="dental-search-progress" aria-label="Wykonane wyszukiwania"><li>{s.solved.day?'✓':'○'} Plan dnia 21.09.2026 — {s.solved.day?'gotowe':'do wykonania'}</li><li>{s.solved.patient?'✓':'○'} Wizyty Ady — {s.solved.patient?'gotowe':'do wykonania'}</li></ul>
   {progress.query&&<p className="dental-message" role="status">Oba wyszukiwania wykonane poprawnie. Odpowiedz na pytania pod symulatorem.</p>}
  </div>}
  <footer className="dental-footer"><p>Dane i projekt pozostają w tej przeglądarce, razem z postępem lekcji. Nauczyciel może obejrzeć je na Twoim ekranie. Wpisuj wyłącznie fikcyjne dane.</p>{reset?<div role="group" aria-label="Potwierdzenie wyczyszczenia bazy"><p>Usunąć projekt, rekordy i wyniki tej symulacji? Tego kroku nie można cofnąć.</p><button type="button" className="btn secondary" onClick={()=>setReset(false)}>Zachowaj bazę</button><button type="button" className="text-button" onClick={()=>{onChange(dentalState());setReset(false);setTab('design');setMessage({ok:true,text:'Symulator wyczyszczony. Możesz zacząć od projektu tabel.'});}}>Tak, wyczyść bazę</button></div>:<button type="button" className="text-button" onClick={()=>setReset(true)}>Zacznij bazę od nowa</button>}</footer>
 </section>;
}

function DentalMessage({message,scope}) {
 return message?.scope===scope?<div className={`dental-message ${message.ok?'':'is-error'}`} role={message.ok?'status':'alert'}>{message.text}</div>:null;
}
