import React,{useEffect,useRef} from 'react';
import {Icon} from './icons.jsx';
export function TeacherDrawer({open,onClose,lesson,stage,onStage,base}){
 const ref=useRef();const section=lesson.sections[stage];
 useEffect(()=>{if(open&&!ref.current.open)ref.current.showModal();else if(!open&&ref.current.open)ref.current.close();},[open]);
 return <dialog ref={ref} className="teacher-drawer" aria-labelledby="teacher-title" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}} onClose={onClose}><div className="drawer-content"><div className="drawer-top"><span><Icon name="school"/> Dla nauczyciela</span><button className="icon-button" aria-label="Zamknij panel nauczyciela" onClick={onClose}><Icon name="close"/></button></div><p className="muted">{lesson.title} · etap {stage+1} z {lesson.sections.length}</p><h2 id="teacher-title">{section.title}</h2><p className="time"><Icon name="clock" size={18}/>{section.duration} min</p><dl className="teacher-notes"><dt>Co powiedzieć i zrobić</dt><dd>{section.teacherNotes}</dd><dt>Zapytaj klasę</dt><dd>„{section.askStudents}”</dd><dt>Oczekiwane odpowiedzi</dt><dd>{section.expectedAnswers}</dd><dt>Częsty błąd</dt><dd>{section.commonMistakes}</dd><dt>Rozszerzenie</dt><dd>{section.optionalExtension}</dd><dt>Gdy brakuje czasu</dt><dd>{section.skipIfShortOnTime?'Skróć tę część lub pomiń rozszerzenie zgodnie ze wskazówką powyżej.':'Zachowaj ten etap; ogranicz liczbę wypowiedzi.'}</dd></dl><div className="inline-actions"><button className="btn secondary" disabled={stage===0} onClick={()=>onStage(stage-1)}><Icon name="left" size={18}/>Poprzedni etap</button><button className="btn secondary" disabled={stage===lesson.sections.length-1} onClick={()=>onStage(stage+1)}>Następny etap<Icon name="right" size={18}/></button></div><a className="text-button" href={`${base}teacher/lesson/${lesson.id}/`}>Otwórz cały plan lekcji <Icon name="external" size={18}/></a><p className="small muted">Panel jest pomocą do prowadzenia zajęć, dostępną bez logowania.</p></div></dialog>
}
export function TeacherTimeline({lesson}){let minute=0;return <ol className="teacher-timeline">{lesson.sections.map(s=>{const start=minute;minute+=s.duration;return <li key={s.id}><span className="timeline-time">{String(start).padStart(2,'0')}:00–{String(minute).padStart(2,'0')}:00</span><div><h3>{s.label}: {s.title}</h3><p>{s.teacherNotes}</p><p><b>Pytanie:</b> {s.askStudents}</p><p><b>Oczekuj:</b> {s.expectedAnswers}</p><p><b>Zadania uczniów:</b> {s.activities.map(a=>a.question||a.title||(a.type==='reveal'?'Odkrywanie kart i porównanie informacji':a.type==='sort'?'Porządkowanie 10 plików':a.type==='flow'?'Odkrywanie kolejnych kroków schematu':a.type==='scenarios'?'Wybór trzech pierwszych działań w czterech przypadkach':a.type==='checklist'?'Samodzielna praca na komputerze':a.type==='hardware'?'Wybór konfiguracji laptopa':a.type==='appNeeds'?'Dobór danych do funkcji aplikacji':null)).filter(Boolean).map(t=>t.replace(/[.!?…]+$/u,'')).join('; ')}.</p><p><b>Uważaj na:</b> {s.commonMistakes}</p><p><b>Rozszerzenie:</b> {s.optionalExtension}</p>{s.skipIfShortOnTime&&<p><b>Przy krótszej lekcji:</b> skróć ten etap lub pomiń rozszerzenie.</p>}</div></li>})}</ol>}
export function TeacherPlan({lesson,base}){return <main tabIndex={-1} id="main" className="teacher-plan"><div className="plan-actions"><a className="text-button" href={`${base}#/lesson/${lesson.id}`}><Icon name="left" size={18}/>Wróć do lekcji</a><button className="btn" onClick={()=>window.print()}><Icon name="printer" size={19}/>Drukuj plan A4</button></div><p className="eyebrow">Klasa {lesson.grade} technikum · Plan dla nauczyciela</p><h1>{lesson.title}</h1><p className="lead">{lesson.subtitle}</p><p><b>Czas:</b> około {lesson.duration} minut. Pozostały czas lekcji można przeznaczyć na organizację i omówienie pracy uczniów.</p><section className="plan-intro"><div><h2>Cele ucznia</h2><ul>{lesson.objectives.map(o=><li key={o}>{o}</li>)}</ul></div><div><h2>Potrzebne materiały</h2><ul>{lesson.materials.map(m=><li key={m}>{m}</li>)}</ul></div></section><h2>Przygotowanie przed lekcją</h2><p>{lesson.teacherGuide.preparation}</p><h2>Przebieg minuta po minucie</h2><TeacherTimeline lesson={lesson}/><h2>Podsumowanie i sprawdzenie</h2><p>{lesson.teacherGuide.summary}</p><p>{lesson.exitTicket}</p><h2>Co można pominąć</h2><p>{lesson.sections.filter(s=>s.skipIfShortOnTime).map(s=>`${s.label}: ${s.optionalExtension}`).join(' ')||'Zachowaj wszystkie etapy, skracając dyskusję.'}</p><p className="print-note">Informatyka praktycznie · {lesson.title} · Materiał do prowadzenia lekcji</p></main>}
